/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectposyandu;
import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Locale;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableCellRenderer;
import koneksi.koneksi;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.autocomplete.ObjectToStringConverter;
/**
 *
 * @author PREDATOR
 */
public class balita extends javax.swing.JPanel {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    public balita() {
        initComponents();
        datatable();
        kosong();
        aktif();
         dataFromDBtoCB();
        bt_hapusdata.setEnabled(false);
        bt_ubahdata.setEnabled(false);
         setBackground(new Color(0,0,0,0));
         DefaultTableCellRenderer head_render = new DefaultTableCellRenderer(); 
        head_render.setBackground(new Color(32, 136, 203));
        Tbalita.getTableHeader().setOpaque(false);
        Tbalita.getTableHeader().setDefaultRenderer(head_render);
        Tbalita.getTableHeader().setForeground(new Color(255,255,255));
        Tbalita.setRowHeight(25);
        AutoCompleteDecorator.decorate(cb_namaibu);
    }
    
    protected void aktif(){
        //k_id.requestFocus();
    }
    protected void kosong(){
        k_id.setText("");
        k_name.setText("");
        k_nik.setText("");
        rjk1.setSelected(false);
        rjk2.setSelected(false);
        k_tl.setCalendar(null);
       
        cb_namaibu.setSelectedItem("");
        k_tinggi.setText("");
        k_berat.setText("");
        
    }
     public void dataFromDBtoCB(){
        try {
            String sql  = "SELECT * FROM ibu";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            
            while (hasil.next()) {                
                cb_namaibu.addItem(hasil.getString("id") + " - " + hasil.getString("nama"));
            }
            
            hasil.last();
            int jumlahdata = hasil.getRow();
            hasil.first();
            
        } catch (SQLException e) {
        }
    }
    
    
   protected void datatable(){
        Object[] Baris = {"Kode Balita","NIK","Nama", "Jenis Kelamin", "Tanggal Lahir", "Tinggi Badan", "Berat Badan", "Umur", "Nama Ibu"};
        tabmode = new DefaultTableModel (null, Baris);
        String findItem = k_cari.getText();
        try {
            String sql = "SELECT * FROM balita where `kd_balita` like '%" + findItem + "%' or `nik` like '%" + findItem + "%' or `nama` like '%" + findItem + "%' order by kd_balita asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String sqlibu = "SELECT * from ibu where id='" + hasil.getString(9) + "'";
                stat = conn.createStatement();
                ResultSet result = stat.executeQuery(sqlibu);
                while(result.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7),
                    hasil.getString(8),
                    result.getString("nama"),
                });
                }
            }
            Tbalita.setModel(tabmode); 
        }catch (Exception e){
             JOptionPane.showMessageDialog(null,"datatable gagal "+e);
           }
        
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        dataBalita = new javax.swing.JPanel();
        bt_tambahdata = new javax.swing.JButton();
        bt_ubahdata = new javax.swing.JButton();
        bt_hapusdata = new javax.swing.JButton();
        label_databalita = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbalita = new javax.swing.JTable();
        bt_hapus = new javax.swing.JButton();
        k_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tambahBalita = new javax.swing.JPanel();
        cb_namaibu = new javax.swing.JComboBox<>();
        k_umur = new javax.swing.JFormattedTextField();
        k_berat = new javax.swing.JFormattedTextField();
        k_tinggi = new javax.swing.JFormattedTextField();
        k_name = new javax.swing.JTextField();
        k_id = new javax.swing.JFormattedTextField();
        k_nik = new javax.swing.JFormattedTextField();
        k_tl = new com.toedter.calendar.JDateChooser();
        label_data1 = new javax.swing.JLabel();
        label_nama1 = new javax.swing.JLabel();
        label_id1 = new javax.swing.JLabel();
        label_tanggallahir2 = new javax.swing.JLabel();
        label_nik1 = new javax.swing.JLabel();
        label_tanggallahir3 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        rjk1 = new javax.swing.JRadioButton();
        rjk2 = new javax.swing.JRadioButton();
        label_tanggallahir10 = new javax.swing.JLabel();
        label_tanggallahir9 = new javax.swing.JLabel();
        label_tanggallahir8 = new javax.swing.JLabel();
        label_tanggallahir4 = new javax.swing.JLabel();
        label_tanggallahir5 = new javax.swing.JLabel();
        label_tanggallahir6 = new javax.swing.JLabel();
        label_tanggallahir7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.CardLayout());

        mainpanel.setBackground(new java.awt.Color(255, 255, 255));
        mainpanel.setOpaque(false);
        mainpanel.setLayout(new java.awt.CardLayout());

        dataBalita.setOpaque(false);
        dataBalita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_tambahdata.setBackground(new java.awt.Color(7, 155, 7));
        bt_tambahdata.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bt_tambahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new_database-5122.png"))); // NOI18N
        bt_tambahdata.setText("Tambah Data");
        bt_tambahdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });
        dataBalita.add(bt_tambahdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 170, 40));

        bt_ubahdata.setBackground(new java.awt.Color(255, 193, 7));
        bt_ubahdata.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bt_ubahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_ubahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/282091.png"))); // NOI18N
        bt_ubahdata.setText("Ubah Data");
        bt_ubahdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        bt_ubahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ubahdataActionPerformed(evt);
            }
        });
        dataBalita.add(bt_ubahdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 690, 180, 40));

        bt_hapusdata.setBackground(new java.awt.Color(255, 0, 51));
        bt_hapusdata.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bt_hapusdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/images__1_-removebg-preview.png"))); // NOI18N
        bt_hapusdata.setText("Hapus Data");
        bt_hapusdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        bt_hapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdataActionPerformed(evt);
            }
        });
        dataBalita.add(bt_hapusdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 690, 170, 40));

        label_databalita.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        label_databalita.setText("DATA BALITA");
        dataBalita.add(label_databalita, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 187, 46));

        Tbalita.setAutoCreateRowSorter(true);
        Tbalita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tbalita.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Tbalita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NIK", "NAMA", "TANGGAL LAHIR", "ALAMAT", "NO TELEPON"
            }
        ));
        Tbalita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tbalita.setIntercellSpacing(new java.awt.Dimension(5, 10));
        Tbalita.setRowHeight(25);
        Tbalita.getTableHeader().setReorderingAllowed(false);
        Tbalita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbalitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbalita);

        dataBalita.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1640, 530));

        bt_hapus.setText("Hapus Data");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });
        dataBalita.add(bt_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 1917, 172, 42));

        k_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        k_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_cariActionPerformed(evt);
            }
        });
        k_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                k_cariKeyReleased(evt);
            }
        });
        dataBalita.add(k_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 294, 36));

        btn_cari.setBackground(new java.awt.Color(242, 242, 242));
        btn_cari.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pngtree-search-flat-yellow-color-icon-seo-find-research-photo-image_19943406-removebg-preview (1).png"))); // NOI18N
        btn_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        btn_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_cariKeyReleased(evt);
            }
        });
        dataBalita.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 40, 36));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ombre-7419016_1280 (1).jpg"))); // NOI18N
        dataBalita.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 980));

        mainpanel.add(dataBalita, "card2");

        tambahBalita.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tambahBalita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_namaibu.setBackground(new java.awt.Color(51, 204, 255));
        cb_namaibu.setForeground(new java.awt.Color(255, 255, 255));
        cb_namaibu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cb_namaibu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tambahBalita.add(cb_namaibu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 420, 50));

        k_umur.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        k_umur.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        k_umur.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_umur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_umurActionPerformed(evt);
            }
        });
        tambahBalita.add(k_umur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, 420, 50));

        k_berat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        k_berat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        k_berat.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_beratActionPerformed(evt);
            }
        });
        tambahBalita.add(k_berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 420, 50));

        k_tinggi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        k_tinggi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        k_tinggi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        k_tinggi.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_tinggiActionPerformed(evt);
            }
        });
        tambahBalita.add(k_tinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 420, 50));

        k_name.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        k_name.setText("`");
        k_name.setToolTipText("");
        k_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 1, true));
        k_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_nameActionPerformed(evt);
            }
        });
        tambahBalita.add(k_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 420, 50));

        k_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        k_id.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        k_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        k_id.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_idActionPerformed(evt);
            }
        });
        tambahBalita.add(k_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 420, 50));

        k_nik.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        k_nik.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        k_nik.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        k_nik.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_nikActionPerformed(evt);
            }
        });
        tambahBalita.add(k_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 420, 50));

        k_tl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tambahBalita.add(k_tl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 280, 50));

        label_data1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        label_data1.setText("DATA BALITA");
        tambahBalita.add(label_data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 187, 46));

        label_nama1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_nama1.setText("NAMA");
        tambahBalita.add(label_nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 136, 30));

        label_id1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_id1.setText("ID");
        tambahBalita.add(label_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 136, 30));

        label_tanggallahir2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_tanggallahir2.setText("Tanggal Lahir");
        tambahBalita.add(label_tanggallahir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 136, 30));

        label_nik1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_nik1.setText("NIK");
        tambahBalita.add(label_nik1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 136, 30));

        label_tanggallahir3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_tanggallahir3.setText("Nama Ibu");
        tambahBalita.add(label_tanggallahir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 136, 30));

        btn_simpan.setBackground(new java.awt.Color(0, 0, 204));
        btn_simpan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/images__2_-removebg-preview (1).png"))); // NOI18N
        btn_simpan.setText("SIMPAN");
        btn_simpan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        tambahBalita.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 730, 185, 40));

        bt_batal.setBackground(new java.awt.Color(204, 60, 37));
        bt_batal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bt_batal.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear (1).png"))); // NOI18N
        bt_batal.setText("BATAL");
        bt_batal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });
        tambahBalita.add(bt_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 730, 185, 40));

        btn_ubah.setBackground(new java.awt.Color(0, 0, 204));
        btn_ubah.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_ubah.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/282091.png"))); // NOI18N
        btn_ubah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btn_ubah.setLabel("UBAH");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        tambahBalita.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 730, 185, 40));
        btn_ubah.getAccessibleContext().setAccessibleDescription("");

        rjk1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rjk1.setText("Laki-Laki");
        rjk1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rjk1MouseClicked(evt);
            }
        });
        tambahBalita.add(rjk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        rjk2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rjk2.setText("Perempuan");
        rjk2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rjk2MouseClicked(evt);
            }
        });
        tambahBalita.add(rjk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        label_tanggallahir10.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_tanggallahir10.setText("Bulan");
        tambahBalita.add(label_tanggallahir10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, 136, 30));

        label_tanggallahir9.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_tanggallahir9.setText("kg");
        tambahBalita.add(label_tanggallahir9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, 136, 30));

        label_tanggallahir8.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_tanggallahir8.setText("cm");
        tambahBalita.add(label_tanggallahir8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 136, 30));

        label_tanggallahir4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_tanggallahir4.setText("T. Badan Lahir");
        tambahBalita.add(label_tanggallahir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 136, 30));

        label_tanggallahir5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_tanggallahir5.setText("B. Badan Lahir");
        tambahBalita.add(label_tanggallahir5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 136, 30));

        label_tanggallahir6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_tanggallahir6.setText("Jenis Kelamin");
        tambahBalita.add(label_tanggallahir6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 136, -1));

        label_tanggallahir7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_tanggallahir7.setText("Umur");
        tambahBalita.add(label_tanggallahir7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, 136, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3169210-removebg-preview.png"))); // NOI18N
        tambahBalita.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ombre-7419016_1280 (1).jpg"))); // NOI18N
        jLabel12.setText("l");
        tambahBalita.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1920, 1380));

        mainpanel.add(tambahBalita, "card3");

        add(mainpanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", " yakin ingin menghapus?", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            System.out.println(k_id);
            String sql = "DELETE FROM balita WHERE kd_balita ="+ k_id.getText() ;
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+ e);
            }
        }
        datatable();
        
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        String findItem = k_cari.getText();
        try{
            String sql = "SELECT * FROM balita where `kd_balita` like '%" + findItem + "%' or `nik` like '%" + findItem + "%' or `nama` like '%" + findItem + "%' order by kd_balita asc";
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
             while (hasil.next()){ 
                  tabmode.addRow(new Object[]{ 
                    hasil.getString(1), 
                    hasil.getString(2), 
                    hasil.getString(3), 
                    hasil.getString(4), 
                    hasil.getString(5) 
                });
             }
             Tbalita.setModel(tabmode);
        } catch (Exception e) { 
            
          }
        datatable();
       
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_cariKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cariKeyReleased

    private void k_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_cariActionPerformed

    private void k_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_k_cariKeyReleased
        // TODO add your handling code here:
        String findItem = k_cari.getText();
         try{
            String sql = "SELECT * FROM balita where `kd_balita` like '%" + findItem + "%' or `nik` like '%" + findItem + "%' or `nama` like '%" + findItem + "%' order by kd_balita asc";
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
             while (hasil.next()){ 
                  tabmode.addRow(new Object[]{ 
                    hasil.getString(1), 
                    hasil.getString(2), 
                    hasil.getString(3), 
                    hasil.getString(4), 
                    hasil.getString(5) 
                });
             }
             Tbalita.setModel(tabmode);
        } catch (Exception e) { 
            
          }
        datatable();
    }//GEN-LAST:event_k_cariKeyReleased

    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(tambahBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        btn_simpan.setVisible(true);
        btn_ubah.setVisible(false);
        k_id.setEditable(false);
        Random rand = new Random();
        Integer random = rand.nextInt(100000);
        k_id.setText(random.toString());
        
       
        
    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void bt_ubahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ubahdataActionPerformed
      mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(tambahBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        btn_ubah.setVisible(true);
        btn_simpan.setVisible(false);
        
        
        
    }//GEN-LAST:event_bt_ubahdataActionPerformed

    private void bt_hapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdataActionPerformed

        if(!k_id.getText().equals("") && !k_id.getText().isEmpty()) {
            bt_hapusdata.setEnabled(true);
            int ok = JOptionPane.showConfirmDialog(null, "hapus", " yakin ingin menghapus?", JOptionPane.YES_NO_OPTION);
            if (ok == 0){
                System.out.println(k_id);
                String sql = "DELETE FROM balita WHERE kd_balita ='"+ k_id.getText() + "'" ;
                try {
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                    kosong();
//                k_id.requestFocus();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, "data gagal dihapus"+ e);
                }
            }
            datatable();      
        } else {
            bt_hapusdata.setEnabled(false);
            JOptionPane.showMessageDialog(null, "tidak ada data yang dihapus");
        }
        
    }//GEN-LAST:event_bt_hapusdataActionPerformed

    private void k_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_nameActionPerformed

    private void k_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_idActionPerformed

    private void k_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_nikActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String jkel="";
        if(rjk1.isSelected()) {
            jkel="Laki-Laki";
            rjk2.setSelected(false);
        }
        else {
            jkel="Perempuan";
            rjk1.setSelected(false);
        }
        if(!k_id.getText().equals("") && !k_nik.getText().equals("") && !k_name.getText().equals("") && !jkel.equals("") && !k_tl.getDate().equals(null)) {
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String Kttl = String.valueOf(fm.format(k_tl.getDate()));
            try {
                String idibu = cb_namaibu.getSelectedItem().toString().replaceAll("[^0-9]", "");
                    String sqlnik = "SELECT nik from balita where nik=" + k_nik.getText();
                    java.sql.Statement statnik = conn.createStatement();
                    ResultSet hasil = statnik.executeQuery(sqlnik);
                    
                    if(!hasil.isBeforeFirst()) {
                        String sql = "INSERT INTO balita values (?,?,?,?,?,?,?,?, ?)";
                        PreparedStatement stat = conn.prepareStatement(sql);
                        stat.setString(1, k_id.getText());
                        stat.setString(2, k_nik.getText());
                        stat.setString(3, k_name.getText());
                        stat.setString(4, jkel);
                        stat.setString(5, Kttl);
                        stat.setString(6, k_tinggi.getText());
                        stat.setString(7, k_berat.getText());
                        stat.setString(8, k_umur.getText());
                        stat.setString(9, idibu);
                        
                        stat.executeUpdate();
                        JOptionPane.showMessageDialog(null, "data berhasil disimpan");
                        mainpanel.removeAll();
                        mainpanel.add(dataBalita);
                        mainpanel.repaint();
                        mainpanel.revalidate();

                    } else {
                        JOptionPane.showMessageDialog(null, "NIK yang diinput sudah terdaftar!");
                        k_nik.setText("");
                    }
                
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal disimpan "+e);
                
            }
        } else {
            JOptionPane.showMessageDialog(null, "Isi semua kolom yang tersedia!");
        }
        datatable();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        mainpanel.removeAll();
        mainpanel.add(dataBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        kosong();
        datatable();
    }//GEN-LAST:event_bt_batalActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try{
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String Kttl = String.valueOf(fm.format(k_tl.getDate()));
            String jkel="";
            if(rjk1.isSelected()) jkel="Laki-Laki";
            else jkel="Perempuan";
                String idibu = cb_namaibu.getSelectedItem().toString().replaceAll("[^0-9]", "");
                String sql = "UPDATE balita set `nama`=?,`nik`=?,`tgl_lahir`=?,`jenis_kelamin`=?, tinggi_badan=?,berat_badan=?, umur=?, id_ibu=? WHERE `kd_balita`=" + k_id.getText();
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, k_name.getText());
                stat.setString(2, k_nik.getText());
                stat.setString(3, Kttl);
                stat.setString(4, jkel);
                stat.setString(5, k_tinggi.getText());
                stat.setString(6, k_berat.getText());
                stat.setString(7, k_umur.getText());
                stat.setString(8, idibu);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                mainpanel.removeAll();
                mainpanel.add(dataBalita);
                mainpanel.repaint();
                mainpanel.revalidate();
                datatable();
                kosong();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah"+ e);
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void TbalitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbalitaMouseClicked
      
        int bar = Tbalita.getSelectedRow();
        String a = tabmode.getValueAt (bar, 0).toString();
        String b = tabmode.getValueAt (bar, 1).toString();
        String c = tabmode.getValueAt (bar, 2).toString();
        String d = tabmode.getValueAt (bar, 3).toString();
        String e = tabmode.getValueAt (bar, 4).toString();
        String f = tabmode.getValueAt (bar, 5).toString();
        String g = tabmode.getValueAt (bar, 6).toString();
        String h = tabmode.getValueAt (bar, 7).toString();
        String i = tabmode.getValueAt (bar, 8).toString();

        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = formatter.parse(e);
            k_tl.setDate(date);
            //        java.util.Date date = formater.parse(b);
        } catch (ParseException ex) {
            Logger.getLogger(balita.class.getName()).log(Level.SEVERE, null, ex);
        }

        // k_id.setText(a);
        if(d.equals("Laki-Laki")) {rjk1.setSelected(true); rjk2.setSelected(false);}
        else {rjk1.setSelected(false); rjk2.setSelected(true);}
        k_id.setText(a);
        k_nik.setText(b);
        k_name.setText(c);
        k_tinggi.setText(f);
        k_berat.setText(g);
        k_umur.setText(h);
        
        try {
            String sql = "SELECT balita.id_ibu AS id_ibu FROM ibu JOIN balita ON ibu.nama = balita.nama where ibu.nama = " + i ;
           Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            rs.next();
            cb_namaibu.setSelectedItem(rs.getString(1));
        } catch (SQLException ev) {
            
        }
       // cb_namaibu.setSelectedItem(h);
      bt_hapusdata.setEnabled(true);
        bt_ubahdata.setEnabled(true);
    }//GEN-LAST:event_TbalitaMouseClicked

    private void k_beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_beratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_beratActionPerformed

    private void k_tinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_tinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_tinggiActionPerformed

    private void rjk1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rjk1MouseClicked
        // TODO add your handling code here:
        rjk2.setSelected(false);
    }//GEN-LAST:event_rjk1MouseClicked

    private void rjk2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rjk2MouseClicked
        // TODO add your handling code here:
        rjk1.setSelected(false);
    }//GEN-LAST:event_rjk2MouseClicked

    private void k_umurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_umurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_umurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tbalita;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_hapusdata;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JButton bt_ubahdata;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox<String> cb_namaibu;
    private javax.swing.JPanel dataBalita;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField k_berat;
    private javax.swing.JTextField k_cari;
    private javax.swing.JFormattedTextField k_id;
    private javax.swing.JTextField k_name;
    private javax.swing.JFormattedTextField k_nik;
    private javax.swing.JFormattedTextField k_tinggi;
    private com.toedter.calendar.JDateChooser k_tl;
    private javax.swing.JFormattedTextField k_umur;
    private javax.swing.JLabel label_data1;
    private javax.swing.JLabel label_databalita;
    private javax.swing.JLabel label_id1;
    private javax.swing.JLabel label_nama1;
    private javax.swing.JLabel label_nik1;
    private javax.swing.JLabel label_tanggallahir10;
    private javax.swing.JLabel label_tanggallahir2;
    private javax.swing.JLabel label_tanggallahir3;
    private javax.swing.JLabel label_tanggallahir4;
    private javax.swing.JLabel label_tanggallahir5;
    private javax.swing.JLabel label_tanggallahir6;
    private javax.swing.JLabel label_tanggallahir7;
    private javax.swing.JLabel label_tanggallahir8;
    private javax.swing.JLabel label_tanggallahir9;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JRadioButton rjk1;
    private javax.swing.JRadioButton rjk2;
    private javax.swing.JPanel tambahBalita;
    // End of variables declaration//GEN-END:variables
}
