/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectposyandu;
import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Locale;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableCellRenderer;
import koneksi.koneksi;

/**
 *
 * @author Asus
 */
public class bidan extends javax.swing.JPanel {
    
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    public bidan() {
        initComponents();
        datatable();
        kosong();
        aktif();
        bhapus_bidan.setEnabled(false);
        bubah_bidan.setEnabled(false);
        
                  setBackground(new Color(0,0,0,0));
         DefaultTableCellRenderer head_render = new DefaultTableCellRenderer(); 
        head_render.setBackground(new Color(32, 136, 203));
        table_bidan.getTableHeader().setOpaque(false);
        table_bidan.getTableHeader().setDefaultRenderer(head_render);
        table_bidan.getTableHeader().setForeground(new Color(255,255,255));
        table_bidan.setRowHeight(25);
    }
    
    protected void aktif(){
        //k_id.requestFocus();
    }
    protected void kosong(){
        tbidan_id.setText("");
        tbidan_nama.setText("");
        tbidan_nik.setText("");
        kbidan_ttl.setCalendar(null);
        tbidan_telp .setText("");
        raktif.setSelected(false);
        rtidak.setSelected(false);
    }
    protected void datatable(){
        Object[] Baris = {"Kode Bidan", "NIK", "Nama", "Tanggal Lahir", "No Telp", "Status"};
        tabmode = new DefaultTableModel (null, Baris);
        
        String cari = tcari_bidan.getText();
        try {
            String sql = "SELECT * FROM bidan where kd_bidan like '%"+cari+"%' or nama like '%"+cari+"%' order by kd_bidan asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6)
                });
            }
            table_bidan.setModel(tabmode); 
        }catch (Exception e){
             JOptionPane.showMessageDialog(null,"datatable gagal "+e);
           }
        
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        dataBidan = new javax.swing.JPanel();
        tcari_bidan = new javax.swing.JTextField();
        label_bidan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_bidan = new javax.swing.JTable();
        bcari_bidan = new javax.swing.JButton();
        bhapus_bidan = new javax.swing.JButton();
        bubah_bidan = new javax.swing.JButton();
        btambah_bidan = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tambahBidan = new javax.swing.JPanel();
        lbidan = new javax.swing.JLabel();
        lbidan_id = new javax.swing.JLabel();
        lbidan_nik = new javax.swing.JLabel();
        lbidan_nama = new javax.swing.JLabel();
        tbidan_nama = new javax.swing.JTextField();
        tbidan_id = new javax.swing.JFormattedTextField();
        tbidan_telp = new javax.swing.JFormattedTextField();
        tbidan_nik = new javax.swing.JFormattedTextField();
        lbidan_ttl = new javax.swing.JLabel();
        kbidan_ttl = new com.toedter.calendar.JDateChooser();
        lbidan_telp = new javax.swing.JLabel();
        lbidan_status = new javax.swing.JLabel();
        raktif = new javax.swing.JRadioButton();
        rtidak = new javax.swing.JRadioButton();
        btnbatal_bidan = new javax.swing.JButton();
        btnubah_bidan = new javax.swing.JButton();
        btnsimpan_bidan = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainpanel.setLayout(new java.awt.CardLayout());

        dataBidan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tcari_bidan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tcari_bidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcari_bidanActionPerformed(evt);
            }
        });
        tcari_bidan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcari_bidanKeyReleased(evt);
            }
        });
        dataBidan.add(tcari_bidan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 294, 36));

        label_bidan.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        label_bidan.setText("DATA BIDAN");
        dataBidan.add(label_bidan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 187, 46));

        table_bidan.setAutoCreateRowSorter(true);
        table_bidan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table_bidan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        table_bidan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NIK", "NAMA", "TANGGAL LAHIR", "ALAMAT", "NO TELEPON"
            }
        ));
        table_bidan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table_bidan.setIntercellSpacing(new java.awt.Dimension(5, 10));
        table_bidan.setRowHeight(25);
        table_bidan.getTableHeader().setReorderingAllowed(false);
        table_bidan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_bidanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_bidan);

        dataBidan.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1640, 530));

        bcari_bidan.setBackground(new java.awt.Color(242, 242, 242));
        bcari_bidan.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bcari_bidan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pngtree-search-flat-yellow-color-icon-seo-find-research-photo-image_19943406-removebg-preview (1).png"))); // NOI18N
        bcari_bidan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        bcari_bidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcari_bidanActionPerformed(evt);
            }
        });
        dataBidan.add(bcari_bidan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 40, 36));

        bhapus_bidan.setBackground(new java.awt.Color(255, 0, 51));
        bhapus_bidan.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bhapus_bidan.setForeground(new java.awt.Color(255, 255, 255));
        bhapus_bidan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/images__1_-removebg-preview.png"))); // NOI18N
        bhapus_bidan.setText("Hapus Data");
        bhapus_bidan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        bhapus_bidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapus_bidanActionPerformed(evt);
            }
        });
        dataBidan.add(bhapus_bidan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 690, 170, 40));

        bubah_bidan.setBackground(new java.awt.Color(255, 193, 7));
        bubah_bidan.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bubah_bidan.setForeground(new java.awt.Color(255, 255, 255));
        bubah_bidan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/282091.png"))); // NOI18N
        bubah_bidan.setText("Ubah Data");
        bubah_bidan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        bubah_bidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubah_bidanActionPerformed(evt);
            }
        });
        dataBidan.add(bubah_bidan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 690, 180, 40));

        btambah_bidan.setBackground(new java.awt.Color(7, 155, 7));
        btambah_bidan.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btambah_bidan.setForeground(new java.awt.Color(255, 255, 255));
        btambah_bidan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new_database-5122.png"))); // NOI18N
        btambah_bidan.setText("Tambah Data");
        btambah_bidan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        btambah_bidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambah_bidanActionPerformed(evt);
            }
        });
        dataBidan.add(btambah_bidan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 170, 40));

        bt_hapus.setText("Hapus Data");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });
        dataBidan.add(bt_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 1917, 172, 42));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ombre-7419016_1280 (1).jpg"))); // NOI18N
        dataBidan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1830, 970));

        mainpanel.add(dataBidan, "card2");

        tambahBidan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbidan.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lbidan.setText("DATA BIDAN");
        tambahBidan.add(lbidan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 187, 46));

        lbidan_id.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lbidan_id.setText("ID");
        tambahBidan.add(lbidan_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 136, 30));

        lbidan_nik.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lbidan_nik.setText("NIK");
        tambahBidan.add(lbidan_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 136, 30));

        lbidan_nama.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lbidan_nama.setText("Nama");
        tambahBidan.add(lbidan_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 136, 30));

        tbidan_nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tambahBidan.add(tbidan_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 420, 50));

        tbidan_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbidan_id.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        tbidan_id.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        tbidan_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbidan_idActionPerformed(evt);
            }
        });
        tambahBidan.add(tbidan_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 420, 50));

        tbidan_telp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbidan_telp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        tbidan_telp.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        tbidan_telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbidan_telpActionPerformed(evt);
            }
        });
        tambahBidan.add(tbidan_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 420, 50));

        tbidan_nik.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbidan_nik.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        tbidan_nik.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        tbidan_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbidan_nikActionPerformed(evt);
            }
        });
        tambahBidan.add(tbidan_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 420, 50));

        lbidan_ttl.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lbidan_ttl.setText("Tanggal Lahir");
        tambahBidan.add(lbidan_ttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 136, 30));

        kbidan_ttl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tambahBidan.add(kbidan_ttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 280, 50));

        lbidan_telp.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lbidan_telp.setText("No Telpon");
        tambahBidan.add(lbidan_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 136, 30));

        lbidan_status.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lbidan_status.setText("Status");
        tambahBidan.add(lbidan_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 136, 30));

        raktif.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        raktif.setText("Aktif");
        tambahBidan.add(raktif, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, -1));

        rtidak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rtidak.setText("Tidak Aktif");
        tambahBidan.add(rtidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        btnbatal_bidan.setBackground(new java.awt.Color(204, 60, 37));
        btnbatal_bidan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnbatal_bidan.setForeground(new java.awt.Color(255, 255, 255));
        btnbatal_bidan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear (1).png"))); // NOI18N
        btnbatal_bidan.setText("BATAL");
        btnbatal_bidan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        btnbatal_bidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatal_bidanActionPerformed(evt);
            }
        });
        tambahBidan.add(btnbatal_bidan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 185, 40));

        btnubah_bidan.setBackground(new java.awt.Color(0, 0, 204));
        btnubah_bidan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnubah_bidan.setForeground(new java.awt.Color(255, 255, 255));
        btnubah_bidan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/282091.png"))); // NOI18N
        btnubah_bidan.setText("UBAH");
        btnubah_bidan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnubah_bidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubah_bidanActionPerformed(evt);
            }
        });
        tambahBidan.add(btnubah_bidan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 185, 40));

        btnsimpan_bidan.setBackground(new java.awt.Color(0, 0, 204));
        btnsimpan_bidan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnsimpan_bidan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan_bidan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/images__2_-removebg-preview (1).png"))); // NOI18N
        btnsimpan_bidan.setText("SIMPAN");
        btnsimpan_bidan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        btnsimpan_bidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpan_bidanActionPerformed(evt);
            }
        });
        tambahBidan.add(btnsimpan_bidan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 185, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ombre-7419016_1280 (1).jpg"))); // NOI18N
        tambahBidan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1830, 970));

        mainpanel.add(tambahBidan, "card3");

        add(mainpanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tcari_bidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcari_bidanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcari_bidanActionPerformed

    private void tcari_bidanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcari_bidanKeyReleased
        // TODO add your handling code here:
        String findItem = tcari_bidan.getText();
        try{
            String sql = "SELECT * FROM bidan where `kd_bidan` like '%" + findItem + "%' or `nik` like '%" + findItem + "%' or `nama` like '%" + findItem + "%' order by kd_bidan asc";
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6)
                });
            }
            table_bidan.setModel(tabmode);
        } catch (Exception e) {

        }
        datatable();
    }//GEN-LAST:event_tcari_bidanKeyReleased

    private void bcari_bidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcari_bidanActionPerformed
        // TODO add your handling code here:
        String findItem = tcari_bidan.getText();

    }//GEN-LAST:event_bcari_bidanActionPerformed

    private void bhapus_bidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapus_bidanActionPerformed
        if(!tbidan_nik.getText().equals("") && !tbidan_nik.getText().isEmpty()) {
            bhapus_bidan.setEnabled(true);
            int ok = JOptionPane.showConfirmDialog(null, "hapus", " yakin ingin menghapus?", JOptionPane.YES_NO_OPTION);
            if (ok == 0){
                System.out.println(tbidan_nik);
                String sql = "DELETE FROM bidan WHERE kd_bidan ='"+ tbidan_id.getText() + "'" ;
                try {
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                    kosong();
//                k_id.requestFocus();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, "data gagal dihapus"+ e);
                }
            }
            datatable();      
        } else {
            bhapus_bidan.setEnabled(false);
            JOptionPane.showMessageDialog(null, "tidak ada data yang dihapus");
        }
    }//GEN-LAST:event_bhapus_bidanActionPerformed

    private void bubah_bidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubah_bidanActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        mainpanel.add(tambahBidan);
        mainpanel.repaint();
        mainpanel.revalidate();
        btnubah_bidan.setVisible(true);
        btnsimpan_bidan.setVisible(false);
        
    }//GEN-LAST:event_bubah_bidanActionPerformed

    private void btambah_bidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambah_bidanActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        mainpanel.add(tambahBidan);
        mainpanel.repaint();
        mainpanel.revalidate();
        btnubah_bidan.setVisible(false);
        btnsimpan_bidan.setVisible(true);
        
        tbidan_id.setEditable(false);
        Random rand = new Random();
        Integer random = rand.nextInt(100000);
        tbidan_id.setText(random.toString());
    }//GEN-LAST:event_btambah_bidanActionPerformed

    private void btnbatal_bidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatal_bidanActionPerformed
        mainpanel.removeAll();
        mainpanel.add(dataBidan);
        mainpanel.repaint();
        mainpanel.revalidate();
        kosong();
        datatable();
    }//GEN-LAST:event_btnbatal_bidanActionPerformed

    private void btnsimpan_bidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpan_bidanActionPerformed

        String status="";
        if(raktif.isSelected()) {
            status="Aktif";
            rtidak.setSelected(false);
        }
        else {
            status="Tidak Aktif";
            raktif.setSelected(false);
        }

        if(!tbidan_id.getText().equals("") && !tbidan_nik.getText().equals("") && !tbidan_nama.getText().equals("") && !status.equals("") && !tbidan_telp.equals("") && !kbidan_ttl.getDate().equals(null)) {
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String Kttl = String.valueOf(fm.format(kbidan_ttl.getDate()));
            try {
                String sqlnik = "SELECT nik from bidan where nik=" + tbidan_nik.getText();
                java.sql.Statement statnik = conn.createStatement();
                ResultSet hasil = statnik.executeQuery(sqlnik);
                if(!hasil.isBeforeFirst()) {
                    String sql = "INSERT INTO bidan values (?,?,?,?,?,?)";
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.setString(1, tbidan_id.getText());
                    stat.setString(2, tbidan_nik.getText());
                    stat.setString(3, tbidan_nama.getText());
                    stat.setString(4, Kttl);
                    stat.setString(5, tbidan_telp.getText());
                    stat.setString(6, status);


                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "data berhasil disimpan");
                    mainpanel.removeAll();
                    mainpanel.add(dataBidan);
                    mainpanel.repaint();
                    mainpanel.revalidate();

                } else {
                    JOptionPane.showMessageDialog(null, "NIK yang diinput sudah terdaftar!");
                    tbidan_nik.setText("");
                }
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal disimpan "+e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Isi semua kolom yang tersedia!");
        }
        datatable();
    }//GEN-LAST:event_btnsimpan_bidanActionPerformed

    private void btnubah_bidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubah_bidanActionPerformed
        // TODO add your handling code here:
                try{
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String Kttl = String.valueOf(fm.format(kbidan_ttl.getDate()));
            String status="";
            if(raktif.isSelected()) status="Aktif";
            else status="Tidak Aktif";
            //            String ibu = k_ibu.getSelectedItem().toString();

            String sql = "UPDATE bidan set `nama`=?, `nik`=?, `tgl_lahir`=?, `status`=?, `no_telp`=? WHERE `kd_bidan`=" + tbidan_id.getText();
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tbidan_nama.getText());
            stat.setString(2, tbidan_nik.getText());
            stat.setString(3, Kttl);
            stat.setString(4, status);
            stat.setString(5, tbidan_telp.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            mainpanel.removeAll();
            mainpanel.add(dataBidan);
            mainpanel.repaint();
            mainpanel.revalidate();
            datatable();
            kosong();
            //   k_id.requestFocus();

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah"+ e);
        }
    }//GEN-LAST:event_btnubah_bidanActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", " yakin ingin menghapus?", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            System.out.println(tbidan_nik);
            String sql = "DELETE FROM bidan WHERE kd_bidan ="+ tbidan_nik.getText() ;
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+ e);
            }
        }
        datatable();

    }//GEN-LAST:event_bt_hapusActionPerformed

    private void table_bidanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_bidanMouseClicked
         
        int bar = table_bidan.getSelectedRow();
        String a = tabmode.getValueAt (bar, 0).toString();
        String b = tabmode.getValueAt (bar, 1).toString();
        String c = tabmode.getValueAt (bar, 2).toString();
        String d = tabmode.getValueAt (bar, 3).toString();
        String e = tabmode.getValueAt (bar, 4).toString();
        String f = tabmode.getValueAt (bar, 5).toString();

        
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = formatter.parse(d);
            kbidan_ttl.setDate(date);
            
            
//        java.util.Date date = formater.parse(b);
        } catch (ParseException ex) {
            Logger.getLogger(bidan.class.getName()).log(Level.SEVERE, null, ex);
        }
    
       if(f.equals("Aktif")) {raktif.setSelected(true); rtidak.setSelected(false);}
        else {raktif.setSelected(false); rtidak.setSelected(true);} 
        tbidan_id.setText(a);
        tbidan_nik.setText(b);
        tbidan_nama.setText(c);
        tbidan_telp.setText(e);
        
        bhapus_bidan.setEnabled(true);
        bubah_bidan.setEnabled(true);
    }//GEN-LAST:event_table_bidanMouseClicked

    private void tbidan_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbidan_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbidan_idActionPerformed

    private void tbidan_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbidan_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbidan_nikActionPerformed

    private void tbidan_telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbidan_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbidan_telpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari_bidan;
    private javax.swing.JButton bhapus_bidan;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton btambah_bidan;
    private javax.swing.JButton btnbatal_bidan;
    private javax.swing.JButton btnsimpan_bidan;
    private javax.swing.JButton btnubah_bidan;
    private javax.swing.JButton bubah_bidan;
    private javax.swing.JPanel dataBidan;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser kbidan_ttl;
    private javax.swing.JLabel label_bidan;
    private javax.swing.JLabel lbidan;
    private javax.swing.JLabel lbidan_id;
    private javax.swing.JLabel lbidan_nama;
    private javax.swing.JLabel lbidan_nik;
    private javax.swing.JLabel lbidan_status;
    private javax.swing.JLabel lbidan_telp;
    private javax.swing.JLabel lbidan_ttl;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JRadioButton raktif;
    private javax.swing.JRadioButton rtidak;
    private javax.swing.JTable table_bidan;
    private javax.swing.JPanel tambahBidan;
    private javax.swing.JFormattedTextField tbidan_id;
    private javax.swing.JTextField tbidan_nama;
    private javax.swing.JFormattedTextField tbidan_nik;
    private javax.swing.JFormattedTextField tbidan_telp;
    private javax.swing.JTextField tcari_bidan;
    // End of variables declaration//GEN-END:variables
}
