/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectposyandu;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Locale;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import koneksi.koneksi;
/**
 *
 * @author PREDATOR
 */
public class Formbalita extends javax.swing.JPanel {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    public Formbalita() {
        initComponents();
        datatable();
        kosong();
        aktif();
        bt_hapusdata.setEnabled(false);
        
    }
    
    protected void aktif(){
        //k_id.requestFocus();
    }
    protected void kosong(){
        //k_id.setText("");
        k_id.setText("");
        k_name.setText("");
        k_nik.setText("");
        //Kttl.setText("");
        rjk1.setSelected(false);
        rjk2.setSelected(false);
        k_tl.setCalendar(null);
       
        //k_ibu.setSelectedItem("");
        //k_alamat.setText("");
        
    }
    protected void datatable(){
        Object[] Baris = {"Kode Balita","NIK","Nama", "Jenis Kelamin", "Tanggal Lahir"};
        tabmode = new DefaultTableModel (null, Baris);
        
        String cari = k_cari.getText();
        try {
            String sql = "SELECT * FROM balita where kd_balita like '%"+cari+"%' or nama like '%"+cari+"%' order by kd_balita asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                
                });
            }
            Tbalita.setModel(tabmode); 
        }catch (Exception e){
             JOptionPane.showMessageDialog(null,"datatable gagal "+e);
           }
        
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        dataBalita = new javax.swing.JPanel();
        bt_tambahdata = new javax.swing.JButton();
        bt_ubahdata = new javax.swing.JButton();
        bt_hapusdata = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbalita = new javax.swing.JTable();
        label_databalita = new javax.swing.JLabel();
        bt_hapus = new javax.swing.JButton();
        k_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tambahBalita = new javax.swing.JPanel();
        k_name = new javax.swing.JTextField();
        k_id = new javax.swing.JFormattedTextField();
        k_nik = new javax.swing.JFormattedTextField();
        k_tl = new com.toedter.calendar.JDateChooser();
        label_data = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        label_tanggallahir = new javax.swing.JLabel();
        label_nik = new javax.swing.JLabel();
        label_tanggallahir1 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        rjk1 = new javax.swing.JRadioButton();
        rjk2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainpanel.setLayout(new java.awt.CardLayout());

        dataBalita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_tambahdata.setBackground(new java.awt.Color(7, 155, 7));
        bt_tambahdata.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bt_tambahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata.setText("Tambah Data");
        bt_tambahdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });
        dataBalita.add(bt_tambahdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 800, 172, 42));

        bt_ubahdata.setBackground(new java.awt.Color(123, 123, 215));
        bt_ubahdata.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bt_ubahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_ubahdata.setText("Ubah Data");
        bt_ubahdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        bt_ubahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ubahdataActionPerformed(evt);
            }
        });
        dataBalita.add(bt_ubahdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 800, 172, 42));

        bt_hapusdata.setBackground(new java.awt.Color(255, 0, 51));
        bt_hapusdata.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bt_hapusdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusdata.setText("Hapus Data");
        bt_hapusdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_hapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdataActionPerformed(evt);
            }
        });
        dataBalita.add(bt_hapusdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 800, 172, 42));

        Tbalita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tbalita.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Tbalita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Tanggal Lahir", "Jenis Kelamin", "Ibu", "Alamat"
            }
        ));
        Tbalita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tbalita.setIntercellSpacing(new java.awt.Dimension(5, 10));
        Tbalita.setMinimumSize(new java.awt.Dimension(105, 800));
        Tbalita.setPreferredSize(new java.awt.Dimension(525, 800));
        Tbalita.setRowHeight(25);
        Tbalita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbalitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbalita);

        dataBalita.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, 1037, 652));

        label_databalita.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        label_databalita.setText("DATA BALITA");
        dataBalita.add(label_databalita, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 8, 187, 46));

        bt_hapus.setText("Hapus Data");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });
        dataBalita.add(bt_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 1917, 172, 42));

        k_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        k_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_cariActionPerformed(evt);
            }
        });
        k_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                k_cariKeyReleased(evt);
            }
        });
        dataBalita.add(k_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 294, 36));

        btn_cari.setBackground(new java.awt.Color(153, 153, 153));
        btn_cari.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_cari.setText("CARI");
        btn_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        btn_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_cariKeyReleased(evt);
            }
        });
        dataBalita.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 123, 36));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ombre-7419016_1280 (1).jpg"))); // NOI18N
        dataBalita.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1830, 970));

        mainpanel.add(dataBalita, "card2");

        tambahBalita.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tambahBalita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        k_name.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        k_name.setText("`");
        k_name.setToolTipText("");
        k_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        k_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_nameActionPerformed(evt);
            }
        });
        tambahBalita.add(k_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 420, 50));

        k_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        k_id.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        k_id.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_idActionPerformed(evt);
            }
        });
        tambahBalita.add(k_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 420, 50));

        k_nik.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        k_nik.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        k_nik.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_nikActionPerformed(evt);
            }
        });
        tambahBalita.add(k_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 420, 50));
        tambahBalita.add(k_tl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 280, 50));

        label_data.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        label_data.setText("DATA BALITA");
        tambahBalita.add(label_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 187, 46));

        label_nama.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_nama.setText("NAMA");
        tambahBalita.add(label_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 136, 30));

        label_id.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_id.setText("ID");
        tambahBalita.add(label_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 136, 30));

        label_tanggallahir.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_tanggallahir.setText("Tanggal Lahir");
        tambahBalita.add(label_tanggallahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 136, 30));

        label_nik.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_nik.setText("NIK");
        tambahBalita.add(label_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 136, 30));

        label_tanggallahir1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_tanggallahir1.setText("Jenis Kelamin");
        tambahBalita.add(label_tanggallahir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 136, 30));

        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        tambahBalita.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 185, 40));

        bt_batal.setText("BATAL");
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });
        tambahBalita.add(bt_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 450, 185, 40));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        tambahBalita.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 185, 40));

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        tambahBalita.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 185, 40));

        rjk1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rjk1.setText("Laki-Laki");
        tambahBalita.add(rjk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        rjk2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rjk2.setText("Perempuan");
        tambahBalita.add(rjk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ombre-7419016_1280 (1).jpg"))); // NOI18N
        jLabel11.setText("l");
        tambahBalita.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1920, 1380));

        mainpanel.add(tambahBalita, "card3");

        add(mainpanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", " yakin ingin menghapus?", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            System.out.println(k_id);
            String sql = "DELETE FROM balita WHERE kd_balita ="+ k_id.getText() ;
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
//                k_id.requestFocus();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+ e);
            }
        }
        datatable();
        
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void TbalitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbalitaMouseClicked
        // TODO add your handling code here:
        
        int bar = Tbalita.getSelectedRow();
        String a = tabmode.getValueAt (bar, 0).toString();
        String b = tabmode.getValueAt (bar, 1).toString();
        String c = tabmode.getValueAt (bar, 2).toString();
        String d = tabmode.getValueAt (bar, 3).toString();
        String e = tabmode.getValueAt (bar, 4).toString();
        
        
//        String tampilan = "dd MMM yyyy";
//        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
//        String Kttl = String.valueOf(fm.format(c));
        //txttl1.setDateFormatString(Kttl);
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = formatter.parse(e);
            k_tl.setDate(date);
            
            
//        java.util.Date date = formater.parse(b);
        } catch (ParseException ex) {
            Logger.getLogger(Formbalita.class.getName()).log(Level.SEVERE, null, ex);
        }
    
       // k_id.setText(a);
       if(d.equals("Laki-Laki")) {rjk1.setSelected(true); rjk2.setSelected(false);}
        else {rjk1.setSelected(false); rjk2.setSelected(true);} 
        k_id.setText(a);
        k_nik.setText(b);
        k_name.setText(c);
        
        bt_hapusdata.setEnabled(true);
        

      
    }//GEN-LAST:event_TbalitaMouseClicked

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try{
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String Kttl = String.valueOf(fm.format(k_tl.getDate()));
            String jkel="";
            if(rjk1.isSelected()) jkel="Laki-Laki";
            else jkel="Perempuan";
            //            String ibu = k_ibu.getSelectedItem().toString();

            String sql = "UPDATE balita set `nama`=?,`nik`=?,`tgl_lahir`=?,`jenis_kelamin`=? WHERE `kd_balita`=" + k_id.getText();
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, k_name.getText());
            stat.setString(2, k_id.getText());
            stat.setString(3, Kttl);
            stat.setString(4, jkel);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUBAH");
            mainpanel.removeAll();
            mainpanel.add(dataBalita);
            mainpanel.repaint();
            mainpanel.revalidate();
            datatable();
            kosong();
            //   k_id.requestFocus();

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah"+ e);
        }

    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "hapus", " yakin ingin menghapus?", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "DELETE FROM balita WHERE id = '"+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                //                k_id.requestFocus();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+ e);
            }
            datatable();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        mainpanel.removeAll();
        mainpanel.add(dataBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        kosong();
        datatable();
    }//GEN-LAST:event_bt_batalActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed

        String jkel="";
            if(rjk1.isSelected()) {
                jkel="Laki-Laki";
                rjk2.setSelected(false);
            }
            else {
                jkel="Perempuan";
                rjk1.setSelected(false);
            }
            

        
        if(!k_id.getText().equals("") && !k_nik.getText().equals("") && !k_name.getText().equals("") && !jkel.equals("") && !k_tl.getDate().equals(null)) {
                    String tampilan = "yyyy-MM-dd";
                    SimpleDateFormat fm = new SimpleDateFormat(tampilan);
                    String Kttl = String.valueOf(fm.format(k_tl.getDate()));
            try {
            String sqlnik = "SELECT nik from balita where nik=" + k_nik.getText();
            java.sql.Statement statnik = conn.createStatement();
            ResultSet hasil = statnik.executeQuery(sqlnik);
              if(!hasil.isBeforeFirst()) {
                        String sql = "INSERT INTO balita values (?,?,?,?,?)";
                        PreparedStatement stat = conn.prepareStatement(sql);
                        stat.setString(1, k_id.getText());
                        stat.setString(2, k_nik.getText());
                        stat.setString(3, k_name.getText());
                        stat.setString(4, jkel);
                        stat.setString(5, Kttl);

                        stat.executeUpdate();
                        JOptionPane.showMessageDialog(null, "data berhasil disimpan");
                        mainpanel.removeAll();
                        mainpanel.add(dataBalita);
                        mainpanel.repaint();
                        mainpanel.revalidate();
                       
              } else {
                  JOptionPane.showMessageDialog(null, "NIK yang diinput sudah terdaftar!");
                  k_nik.setText("");
              }
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan "+e);
        }
        } else {
            JOptionPane.showMessageDialog(null, "Isi semua kolom yang tersedia!");
        }
        datatable();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void k_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_nameActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        String findItem = k_cari.getText();
       
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_cariKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cariKeyReleased

    private void k_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_cariActionPerformed

    private void k_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_k_cariKeyReleased
        // TODO add your handling code here:
        String findItem = k_cari.getText();
         try{
            String sql = "SELECT * FROM balita where `kd_balita` like '%" + findItem + "%' or `nik` like '%" + findItem + "%' or `nama` like '%" + findItem + "%' order by kd_balita asc";
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
             while (hasil.next()){ 
                  tabmode.addRow(new Object[]{ 
                    hasil.getString(1), 
                    hasil.getString(2), 
                    hasil.getString(3), 
                    hasil.getString(4), 
                    hasil.getString(5) 
                });
             }
             Tbalita.setModel(tabmode);
        } catch (Exception e) { 
            
          }
        datatable();
    }//GEN-LAST:event_k_cariKeyReleased

    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(tambahBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        btn_simpan.setVisible(true);
        btn_ubah.setVisible(false);
        btn_hapus.setVisible(false);
        
        k_id.setEditable(false);
        Random rand = new Random();
        Integer random = rand.nextInt(100000);
        k_id.setText(random.toString());
        
       
        
    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void bt_ubahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ubahdataActionPerformed
      mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(tambahBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        btn_ubah.setVisible(true);
        btn_hapus.setVisible(false);
        btn_simpan.setVisible(false);
        
    }//GEN-LAST:event_bt_ubahdataActionPerformed

    private void bt_hapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdataActionPerformed

        if(!k_id.getText().equals("") && !k_id.getText().isEmpty()) {
            bt_hapusdata.setEnabled(true);
            int ok = JOptionPane.showConfirmDialog(null, "hapus", " yakin ingin menghapus?", JOptionPane.YES_NO_OPTION);
            if (ok == 0){
                System.out.println(k_id);
                String sql = "DELETE FROM balita WHERE kd_balita ='"+ k_id.getText() + "'" ;
                try {
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                    kosong();
//                k_id.requestFocus();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, "data gagal dihapus"+ e);
                }
            }
            datatable();      
        } else {
            bt_hapusdata.setEnabled(false);
            JOptionPane.showMessageDialog(null, "tidak ada data yang dihapus");
        }
        
    }//GEN-LAST:event_bt_hapusdataActionPerformed

    private void k_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_idActionPerformed

    private void k_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_nikActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tbalita;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_hapusdata;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JButton bt_ubahdata;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JPanel dataBalita;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField k_cari;
    private javax.swing.JFormattedTextField k_id;
    private javax.swing.JTextField k_name;
    private javax.swing.JFormattedTextField k_nik;
    private com.toedter.calendar.JDateChooser k_tl;
    private javax.swing.JLabel label_data;
    private javax.swing.JLabel label_databalita;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_nik;
    private javax.swing.JLabel label_tanggallahir;
    private javax.swing.JLabel label_tanggallahir1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JRadioButton rjk1;
    private javax.swing.JRadioButton rjk2;
    private javax.swing.JPanel tambahBalita;
    // End of variables declaration//GEN-END:variables
}
