/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectposyandu;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import koneksi.koneksi;
/**
 *
 * @author PREDATOR
 */
public class Formbalita extends javax.swing.JPanel {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    public Formbalita() {
        initComponents();
        
        kosong();
        aktif();
        datatable();
    }
    
    protected void aktif(){
        Kid.requestFocus();
    }
    protected void kosong(){
        Kid.setText("");
        KNama.setText("");
        Kttl.setText("");
        Kjk.setText("");
        Kibu.setText("");
        Kalamat.setText("");
        
    }
    protected void datatable(){
        Object[] Baris = {"Id","Nama","Tanggal Lahir", "Jenis Kelamin", "Ibu", "Alamat"};
        tabmode = new DefaultTableModel (null, Baris);
        
        String cari = Kcari.getText();
        try {
            String sql = "SELECT * FROM balita where Id like '%"+cari+"%' or Nama like '%"+cari+"%' order by Id asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6)
                
                });
            }
            Tbalita.setModel(tabmode); 
        }catch (Exception e){
             JOptionPane.showMessageDialog(null,"datatable gagal "+e);
           }
        
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        dataBalita = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbalita = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bt_tambahdata = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        bt_Ubah = new javax.swing.JButton();
        Kcari = new javax.swing.JTextField();
        bt_cari = new javax.swing.JButton();
        tambahBalita = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bt_simpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        KNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Kid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Kttl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Kjk = new javax.swing.JTextField();
        Kibu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Kalamat = new javax.swing.JTextField();
        bt_ubah2 = new javax.swing.JButton();
        hapusbalita = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        bt_hapusdata = new javax.swing.JButton();
        bt_batal2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        KNama2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Kid2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Kttl2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Kjk2 = new javax.swing.JTextField();
        Kibu2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Kalamat2 = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        mainpanel.setLayout(new java.awt.CardLayout());

        Tbalita.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        Tbalita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Tanggal Lahir", "Jenis Kelamin", "Ibu", "Alamat"
            }
        ));
        Tbalita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tbalita.setIntercellSpacing(new java.awt.Dimension(5, 10));
        Tbalita.setRowHeight(25);
        Tbalita.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tbalita);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("DATA BALITA");

        bt_tambahdata.setText("Tambah Data");
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });

        bt_hapus.setText("Hapus Data");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_Ubah.setText("Ubah Data");
        bt_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_UbahActionPerformed(evt);
            }
        });

        bt_cari.setText("CARI");

        javax.swing.GroupLayout dataBalitaLayout = new javax.swing.GroupLayout(dataBalita);
        dataBalita.setLayout(dataBalitaLayout);
        dataBalitaLayout.setHorizontalGroup(
            dataBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBalitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1820, Short.MAX_VALUE)
                    .addGroup(dataBalitaLayout.createSequentialGroup()
                        .addGroup(dataBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataBalitaLayout.createSequentialGroup()
                                .addComponent(Kcari, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dataBalitaLayout.createSequentialGroup()
                                .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1268, Short.MAX_VALUE))))
        );
        dataBalitaLayout.setVerticalGroup(
            dataBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBalitaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dataBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Kcari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        mainpanel.add(dataBalita, "card2");

        tambahBalita.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tambahBalita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setText("DATA BALITA");
        tambahBalita.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 187, 46));

        bt_simpan.setText("SIMPAN");
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });
        tambahBalita.add(bt_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 180, 42));

        bt_batal.setText("BATAL");
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });
        tambahBalita.add(bt_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 172, 42));

        jLabel3.setText("id");
        tambahBalita.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 147, 78, 38));
        tambahBalita.add(KNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 212, 523, 40));

        jLabel4.setText("Nama");
        tambahBalita.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 224, 78, -1));
        tambahBalita.add(Kid, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 147, 523, 38));

        jLabel5.setText("Tanggal Lahir");
        tambahBalita.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 283, -1, 35));
        tambahBalita.add(Kttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 280, 523, 40));

        jLabel6.setText("Jenis Kelamin");
        tambahBalita.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 350, 78, 35));
        tambahBalita.add(Kjk, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 347, 523, 40));

        Kibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KibuActionPerformed(evt);
            }
        });
        tambahBalita.add(Kibu, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 414, 523, 40));

        jLabel7.setText("Ibu");
        tambahBalita.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 417, 78, 35));

        jLabel8.setText("Alamat ");
        tambahBalita.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 472, 109, 39));
        tambahBalita.add(Kalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 480, 523, 36));

        bt_ubah2.setText("UBAH");
        bt_ubah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ubah2ActionPerformed(evt);
            }
        });
        tambahBalita.add(bt_ubah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 529, 172, 42));

        mainpanel.add(tambahBalita, "card2");

        hapusbalita.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel16.setText("DATA BALITA");

        bt_hapusdata.setText("HAPUS");
        bt_hapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdataActionPerformed(evt);
            }
        });

        bt_batal2.setText("BATAL");
        bt_batal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batal2ActionPerformed(evt);
            }
        });

        jLabel17.setText("id");

        jLabel18.setText("Nama");

        jLabel19.setText("Tanggal Lahir");

        jLabel20.setText("Jenis Kelamin");

        Kibu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kibu2ActionPerformed(evt);
            }
        });

        jLabel21.setText("Ibu");

        jLabel22.setText("Alamat ");

        javax.swing.GroupLayout hapusbalitaLayout = new javax.swing.GroupLayout(hapusbalita);
        hapusbalita.setLayout(hapusbalitaLayout);
        hapusbalitaLayout.setHorizontalGroup(
            hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusbalitaLayout.createSequentialGroup()
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hapusbalitaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hapusbalitaLayout.createSequentialGroup()
                                .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_batal2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hapusbalitaLayout.createSequentialGroup()
                                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(KNama2)
                                    .addComponent(Kid2)
                                    .addComponent(Kttl2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                    .addComponent(Kjk2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                    .addComponent(Kibu2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                    .addComponent(Kalamat2)))))
                    .addGroup(hapusbalitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1136, Short.MAX_VALUE))
        );
        hapusbalitaLayout.setVerticalGroup(
            hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusbalitaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Kid2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KNama2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(28, 28, 28)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kttl2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kjk2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kibu2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(hapusbalitaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Kalamat2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(465, Short.MAX_VALUE))
        );

        mainpanel.add(hapusbalita, "card2");

        add(mainpanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
       String sql = "INSERT INTO balita values (?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, Kid.getText());
            stat.setString(2, KNama.getText());
            stat.setString(3, Kttl.getText());
            stat.setString(4, Kjk.getText());
            stat.setString(5, Kibu.getText());
            stat.setString(6, Kalamat.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            Kid.requestFocus();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan "+e);
        }
        datatable();
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void KibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KibuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KibuActionPerformed

    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(tambahBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        bt_ubah2.setVisible(false);
        bt_simpan.setVisible(true);
        
        
    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        mainpanel.removeAll();
        mainpanel.add(dataBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        kosong();
        datatable();
    }//GEN-LAST:event_bt_batalActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(hapusbalita);
        mainpanel.repaint();
        
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_hapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdataActionPerformed
        
        int ok = JOptionPane.showConfirmDialog(null, "hapus", " yakin ingin menghapus?", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "DELETE FROM balita WHERE id = '"+Kid.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                Kid.requestFocus();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+ e);
            }
            datatable();
        }
    }//GEN-LAST:event_bt_hapusdataActionPerformed

    private void bt_batal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batal2ActionPerformed
        mainpanel.removeAll();
        mainpanel.add(dataBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        kosong();
        datatable();
    }//GEN-LAST:event_bt_batal2ActionPerformed

    private void Kibu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kibu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kibu2ActionPerformed

    private void bt_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_UbahActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(tambahBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        bt_ubah2.setVisible(true);
        bt_simpan.setVisible(false);
    }//GEN-LAST:event_bt_UbahActionPerformed

    private void bt_ubah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ubah2ActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(tambahBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        try{
            String sql = "UPDATE balita set Id=?,Nama=?,Tanggal Lahir=?,Jenis Kelamin=?,Ibu=?,Alamat=? where Id ='"+Kid.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, Kid.getText());
            stat.setString(2, KNama.getText());
            stat.setString(3, Kttl.getText());
            stat.setString(4, Kjk.getText());
            stat.setString(5, Kibu.getText());
            stat.setString(6, Kalamat.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI UBAH");
            kosong();
            Kid.requestFocus();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah"+ e);
        }
        datatable();
    }//GEN-LAST:event_bt_ubah2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KNama;
    private javax.swing.JTextField KNama2;
    private javax.swing.JTextField Kalamat;
    private javax.swing.JTextField Kalamat2;
    private javax.swing.JTextField Kcari;
    private javax.swing.JTextField Kibu;
    private javax.swing.JTextField Kibu2;
    private javax.swing.JTextField Kid;
    private javax.swing.JTextField Kid2;
    private javax.swing.JTextField Kjk;
    private javax.swing.JTextField Kjk2;
    private javax.swing.JTextField Kttl;
    private javax.swing.JTextField Kttl2;
    private javax.swing.JTable Tbalita;
    private javax.swing.JButton bt_Ubah;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_batal2;
    private javax.swing.JButton bt_cari;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_hapusdata;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JButton bt_ubah2;
    private javax.swing.JPanel dataBalita;
    private javax.swing.JPanel hapusbalita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel tambahBalita;
    // End of variables declaration//GEN-END:variables
}
