/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectposyandu;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import koneksi.koneksi;

/**
 *
 * @author PREDATOR
 */
public class ibu extends javax.swing.JPanel {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;

    
    public ibu() {
        initComponents();
        kosong();
        aktif();
        datatable();
    }
    
    protected void aktif(){
        k_id.requestFocus();
    }
    protected void kosong(){
        k_id.setText("");
        k_nik.setText("");
        k_nama.setText("");
        k_tl.setText("");
        k_alamat.setText("");
        k_notelp.setText("");
        k_status.setText("");
        
    }
    protected void datatable(){
        Object[] Baris = {"ID","NIK","NAMA", "TANGGAL LAHIR", "ALAMAT", "NO TELPON", "STATUS"};
        tabmode = new DefaultTableModel (null, Baris);
        
        String cari = Kcari.getText();
        try {
            String sql = "SELECT * FROM balita where ID like '%"+cari+"%' or NAMA like '%"+cari+"%' order by ID asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7)
                
                });
            }
            Tibu.setModel(tabmode); 
        }catch (Exception e){
             JOptionPane.showMessageDialog(null,"datatable gagal "+e);
           }
        
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        dataibu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tibu = new javax.swing.JTable();
        Kcari = new javax.swing.JTextField();
        bt_cari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt_tambahdata = new javax.swing.JButton();
        bt_hapusdata = new javax.swing.JButton();
        bt_ubahdata = new javax.swing.JButton();
        TU = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bt_ubah2 = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bt_simpan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        k_alamat = new javax.swing.JTextArea();
        k_status = new javax.swing.JTextField();
        k_id = new javax.swing.JTextField();
        k_nik = new javax.swing.JTextField();
        k_nama = new javax.swing.JTextField();
        k_tl = new javax.swing.JTextField();
        k_notelp = new javax.swing.JTextField();
        bt_hapus2 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainpanel.setLayout(new java.awt.CardLayout());

        Tibu.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        Tibu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NIK", "NAMA", "ALAMAT", "TANGGAL LAHIR", "NO TELEPON", "STATUS"
            }
        ));
        Tibu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tibu.setIntercellSpacing(new java.awt.Dimension(5, 10));
        Tibu.setRowHeight(25);
        Tibu.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tibu);

        bt_cari.setText("CARI");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("DATA IBU");

        bt_tambahdata.setText("Tambah Data");
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });

        bt_hapusdata.setText("Hapus Data");
        bt_hapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdataActionPerformed(evt);
            }
        });

        bt_ubahdata.setText("Ubah Data");
        bt_ubahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ubahdataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataibuLayout = new javax.swing.GroupLayout(dataibu);
        dataibu.setLayout(dataibuLayout);
        dataibuLayout.setHorizontalGroup(
            dataibuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataibuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataibuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataibuLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(dataibuLayout.createSequentialGroup()
                        .addGroup(dataibuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataibuLayout.createSequentialGroup()
                                .addComponent(Kcari, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dataibuLayout.createSequentialGroup()
                                .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_ubahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 594, Short.MAX_VALUE))))
        );
        dataibuLayout.setVerticalGroup(
            dataibuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataibuLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dataibuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Kcari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataibuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ubahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        mainpanel.add(dataibu, "card2");

        TU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setText("DATA IBU");
        TU.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 187, 46));

        jLabel3.setText("ID");
        TU.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, 136, 30));

        jLabel4.setText("NIK");
        TU.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 136, 30));

        jLabel5.setText("NAMA");
        TU.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 136, 30));

        jLabel6.setText("TANGGAL LAHIR");
        TU.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 136, 30));

        jLabel7.setText("ALAMAT");
        TU.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 136, 40));

        jLabel8.setText("NO TELP");
        TU.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 136, 30));

        bt_ubah2.setText("UBAH");
        bt_ubah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ubah2ActionPerformed(evt);
            }
        });
        TU.add(bt_ubah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, 185, 40));

        bt_batal.setText("BATAL");
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });
        TU.add(bt_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 185, 40));

        jLabel9.setText("STATUS");
        TU.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 136, 30));

        bt_simpan.setText("SIMPAN");
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });
        TU.add(bt_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, 185, 40));

        k_alamat.setColumns(20);
        k_alamat.setRows(5);
        jScrollPane3.setViewportView(k_alamat);

        TU.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 420, -1));
        TU.add(k_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 420, 50));

        k_id.setText("`");
        TU.add(k_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 112, 420, 50));
        TU.add(k_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 420, 50));

        k_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_namaActionPerformed(evt);
            }
        });
        TU.add(k_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 420, 50));
        TU.add(k_tl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 420, 50));
        TU.add(k_notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 420, 50));

        bt_hapus2.setText("HAPUS");
        bt_hapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapus2ActionPerformed(evt);
            }
        });
        TU.add(bt_hapus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, 185, 40));

        mainpanel.add(TU, "card2");

        add(mainpanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(TU);
        mainpanel.repaint();
        mainpanel.revalidate();
        bt_ubah2.setVisible(false);
        bt_simpan.setVisible(true);
        bt_hapus2.setVisible(false);

    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void bt_hapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdataActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(TU);
        mainpanel.repaint();
        bt_ubah2.setVisible(false);
        bt_simpan.setVisible(false);
        bt_hapus2.setVisible(true);

    }//GEN-LAST:event_bt_hapusdataActionPerformed

    private void bt_ubahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ubahdataActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(TU);
        mainpanel.repaint();
        mainpanel.revalidate();
        bt_ubah2.setVisible(true);
        bt_simpan.setVisible(false);
        bt_hapus2.setVisible(false);
    }//GEN-LAST:event_bt_ubahdataActionPerformed

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
        String sql = "INSERT INTO balita values (?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, k_id.getText());
            stat.setString(2, k_nik.getText());
            stat.setString(3, k_nama.getText());
            stat.setString(4, k_tl.getText());
            stat.setString(5, k_alamat.getText());
            stat.setString(6, k_notelp.getText());
            stat.setString(7, k_status.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            k_id.requestFocus();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan "+e);
        }
        datatable();
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_batalActionPerformed

    private void bt_ubah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ubah2ActionPerformed
        try{
            String sql = "UPDATE balita set ID=?,NIK=?,NAMA=?,TANGGAL LAHIR=?,ALAMAT=?,NO TELPON=?,STATUS=? where ID ='"+k_id.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, k_id.getText());
            stat.setString(2, k_nik.getText());
            stat.setString(3, k_nama.getText());
            stat.setString(4, k_tl.getText());
            stat.setString(5, k_alamat.getText());
            stat.setString(6, k_notelp.getText());
            stat.setString(7, k_status.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI UBAH");
            kosong();
            k_id.requestFocus();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah"+ e);
        }
        datatable();
    }//GEN-LAST:event_bt_ubah2ActionPerformed

    private void k_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_namaActionPerformed

    private void bt_hapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapus2ActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", " yakin ingin menghapus?", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "DELETE FROM balita WHERE id = '"+k_id.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                k_id.requestFocus();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+ e);
            }
            datatable();
        }
    }//GEN-LAST:event_bt_hapus2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Kcari;
    private javax.swing.JPanel TU;
    private javax.swing.JTable Tibu;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_cari;
    private javax.swing.JButton bt_hapus2;
    private javax.swing.JButton bt_hapusdata;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JButton bt_ubah2;
    private javax.swing.JButton bt_ubahdata;
    private javax.swing.JPanel dataibu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea k_alamat;
    private javax.swing.JTextField k_id;
    private javax.swing.JTextField k_nama;
    private javax.swing.JTextField k_nik;
    private javax.swing.JTextField k_notelp;
    private javax.swing.JTextField k_status;
    private javax.swing.JTextField k_tl;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
