/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectposyandu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.koneksi;
/**
 *
 * @author PREDATOR
 */
public class login extends javax.swing.JFrame {
    int xx, xy;
    private Connection conn = new koneksi().connect();

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        btn_regist.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        mainpanel2 = new javax.swing.JPanel();
        panellogin = new javax.swing.JPanel();
        label_toregist = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kpassword = new javax.swing.JPasswordField();
        kpassword1 = new javax.swing.JPasswordField();
        kusername = new javax.swing.JTextField();
        ic_posyandu = new javax.swing.JLabel();
        ic_close = new javax.swing.JLabel();
        Blogin = new javax.swing.JButton();
        ic_profile = new javax.swing.JLabel();
        ic_key = new javax.swing.JLabel();
        bg_login = new javax.swing.JLabel();
        bg_ibu = new javax.swing.JLabel();
        wp = new javax.swing.JLabel();
        panelregist = new javax.swing.JPanel();
        k_pass = new javax.swing.JPasswordField();
        label_login = new javax.swing.JLabel();
        label_close = new javax.swing.JLabel();
        posyandu = new javax.swing.JLabel();
        k_idkader = new javax.swing.JTextField();
        btn_regist = new javax.swing.JButton();
        label_kunci = new javax.swing.JLabel();
        label_sudah = new javax.swing.JLabel();
        k_user = new javax.swing.JTextField();
        btn_cek = new javax.swing.JButton();
        label_profil = new javax.swing.JLabel();
        label_idc = new javax.swing.JLabel();
        bg_regis2 = new javax.swing.JLabel();
        ibu = new javax.swing.JLabel();
        bg_regis1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        mainpanel2.setLayout(new java.awt.CardLayout());

        panellogin.setBackground(new java.awt.Color(255, 255, 255));
        panellogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_toregist.setText("Tidak mempunyai akun?");
        panellogin.add(label_toregist, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Register");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panellogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));

        kpassword.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        kpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.blue));
        kpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kpasswordActionPerformed(evt);
            }
        });
        panellogin.add(kpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 350, 40));

        kpassword1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        kpassword1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.blue));
        kpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kpassword1ActionPerformed(evt);
            }
        });
        panellogin.add(kpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 350, 40));

        kusername.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        kusername.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.blue));
        kusername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        kusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kusernameActionPerformed(evt);
            }
        });
        panellogin.add(kusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 350, 40));

        ic_posyandu.setBackground(new java.awt.Color(102, 153, 255));
        ic_posyandu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Posyandu 2021 Logo (PNG1080p) - Vector69Com (3).png"))); // NOI18N
        panellogin.add(ic_posyandu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        ic_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close_3.png"))); // NOI18N
        ic_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ic_closeMouseClicked(evt);
            }
        });
        panellogin.add(ic_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 30, 30));

        Blogin.setText("LOG IN");
        Blogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(0, 153, 255)));
        Blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloginActionPerformed(evt);
            }
        });
        panellogin.add(Blogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 110, 30));

        ic_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Contacts_3.png"))); // NOI18N
        panellogin.add(ic_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 50, 60));

        ic_key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Key_7.png"))); // NOI18N
        panellogin.add(ic_key, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 60, 40));

        bg_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/baks3 (1).png"))); // NOI18N
        bg_login.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panellogin.add(bg_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 580, 390));

        bg_ibu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/—Pngtree—mother with her girl illustration_14269801 (1) (3).png"))); // NOI18N
        panellogin.add(bg_ibu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 590, 660));

        wp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ombre-7419016_1280.jpg"))); // NOI18N
        panellogin.add(wp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));

        mainpanel2.add(panellogin, "card2");

        panelregist.setBackground(new java.awt.Color(255, 255, 255));
        panelregist.setMinimumSize(new java.awt.Dimension(1070, 660));
        panelregist.setPreferredSize(new java.awt.Dimension(1070, 660));
        panelregist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        k_pass.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        k_pass.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.blue));
        k_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_passActionPerformed(evt);
            }
        });
        panelregist.add(k_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 350, 40));

        label_login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_login.setForeground(new java.awt.Color(102, 255, 255));
        label_login.setText("Login");
        label_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_loginMouseClicked(evt);
            }
        });
        panelregist.add(label_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 498, -1, -1));

        label_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close_3.png"))); // NOI18N
        label_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_closeMouseClicked(evt);
            }
        });
        panelregist.add(label_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 30, 30));

        posyandu.setBackground(new java.awt.Color(102, 153, 255));
        posyandu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Posyandu 2021 Logo (PNG1080p) - Vector69Com (3).png"))); // NOI18N
        panelregist.add(posyandu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        k_idkader.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        k_idkader.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.blue));
        k_idkader.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        k_idkader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_idkaderActionPerformed(evt);
            }
        });
        panelregist.add(k_idkader, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 350, 40));

        btn_regist.setText("REGISTER");
        btn_regist.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(0, 153, 255)));
        btn_regist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registActionPerformed(evt);
            }
        });
        panelregist.add(btn_regist, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 110, 30));

        label_kunci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Key_7.png"))); // NOI18N
        panelregist.add(label_kunci, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 60, 40));

        label_sudah.setText("Sudah mempunyai akun?");
        panelregist.add(label_sudah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        k_user.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        k_user.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.blue));
        k_user.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        k_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_userActionPerformed(evt);
            }
        });
        panelregist.add(k_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 350, 40));

        btn_cek.setText("Cek ID");
        btn_cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekActionPerformed(evt);
            }
        });
        panelregist.add(btn_cek, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        label_profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Contacts_3.png"))); // NOI18N
        panelregist.add(label_profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 50, 60));

        label_idc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/id_card.png"))); // NOI18N
        panelregist.add(label_idc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 40, 60));

        bg_regis2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/baks35.png"))); // NOI18N
        bg_regis2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelregist.add(bg_regis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 580, 340));

        ibu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/—Pngtree—mother with her girl illustration_14269801 (1) (3).png"))); // NOI18N
        panelregist.add(ibu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 590, 660));

        bg_regis1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ombre-7419016_1280.jpg"))); // NOI18N
        panelregist.add(bg_regis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 660));

        mainpanel2.add(panelregist, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void btn_cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekActionPerformed
        // TODO add your handling code here:
        try {
                if(k_idkader.getText() != null && !k_idkader.getText().isEmpty() && !k_idkader.getText().equals("")) {
                    String sql = "SELECT id from kader where id=" + k_idkader.getText();
                    java.sql.Statement stat = conn.createStatement();
                    ResultSet hasil = stat.executeQuery(sql);
                     if(!hasil.isBeforeFirst()) {
                        JOptionPane.showMessageDialog(null, "ID tidak ditemukan, silahkan masukkan kembali ID yang benar");
                        btn_regist.setEnabled(false);
                     } else {
                        System.out.println("1");
                        String sql2 = "SELECT id_kader from user";
                        stat = conn.createStatement();
                        ResultSet hasil2 = stat.executeQuery(sql2);
                        if(!hasil2.isBeforeFirst()) {
                            System.out.println("15");
                        } else {
                            hasil2.next();
                                if(k_idkader.getText().equals(hasil2.getString(1))) {
                                    System.out.println("2");
                                    JOptionPane.showMessageDialog(null, "ID sudah terdaftar, silahkan login");
                                    btn_regist.setEnabled(false);
                                } else {
                                    JOptionPane.showMessageDialog(null, "ID belum dipakai, silahkan lanjut");
                                    btn_regist.setEnabled(true);
                                }
                        }
                     }
//                    } else if(!hasil.isBeforeFirst()) {
//                        //System.out.println(k_idkader.getText());
//                        //System.out.println("tidak ditemukan");
//                        System.out.println("3");
//                        JOptionPane.showMessageDialog(null, "ID tidak ditemukan, silahkan login");
//                        J
//                    }
                       
                } else {
                    btn_regist.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "Masukkan ID Kader");
                }
                
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_cekActionPerformed

    private void k_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_userActionPerformed

    private void btn_registActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registActionPerformed
        // TODO add your handling code here:
        
        if(!k_idkader.getText().equals(null) && !k_user.getText().equals(null) && !k_pass.getText().equals(null) && !k_idkader.getText().isEmpty() && !k_user.getText().equals("") && !k_pass.getText().equals("")) {
            try {
                String sql = "INSERT into user values (?,?,?) ";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, k_idkader.getText());
                stat.setString(2, k_user.getText());
                stat.setString(3, k_pass.getText());
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil disimpan");
                //kosong();
                k_idkader.requestFocus();
                mainpanel2.removeAll();
                mainpanel2.repaint();
                mainpanel2.revalidate();

                mainpanel2.add(panellogin);
                mainpanel2.repaint();
                mainpanel2.revalidate();
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal disimpan "+e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Masukkan data yang ada!");
        }
    }//GEN-LAST:event_btn_registActionPerformed

    private void k_idkaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_idkaderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_idkaderActionPerformed

    private void label_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_closeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_closeMouseClicked

    private void k_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_passActionPerformed

    private void BloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloginActionPerformed
    if(!kusername.getText().equals("") && !kpassword.getText().equals("")) {
        try {
                System.out.println("1");
                String sql = "SELECT * from user where user='" + kusername.getText() + "'";
                java.sql.Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                if(!hasil.isBeforeFirst()) {
                        JOptionPane.showMessageDialog(null, "username tidak ditemukan, periksa kembali username yang anda masukkan!");
                        kusername.setText("");
                        kpassword.setText("");
                        kusername.requestFocus(true);
                     } else {
                    hasil.next();
                    if(kpassword.getText().equals(hasil.getString(3))) {
                        JOptionPane.showMessageDialog(null, "Login succes");
                        main Main = new main();
                        Main.setVisible(true);
                        Main.revalidate();
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Password yang anda masukkan salah!");
                        kpassword.setText("");
                        kusername.requestFocus(true);
                    }
                }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal disimpan "+e);
          }
    } else {
                System.out.println("3");
                JOptionPane.showMessageDialog(null, "Masukkan Username");
            }
       
    }//GEN-LAST:event_BloginActionPerformed

    private void kusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kusernameActionPerformed

    private void ic_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_closeMouseClicked
        dispose();
    }//GEN-LAST:event_ic_closeMouseClicked

    private void kpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kpasswordActionPerformed

    private void label_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_loginMouseClicked
        // TODO add your handling code here:
        mainpanel2.removeAll();
        mainpanel2.repaint();
        mainpanel2.revalidate();

        mainpanel2.add(panellogin);
        mainpanel2.repaint();
        mainpanel2.revalidate();
        
    }//GEN-LAST:event_label_loginMouseClicked

    private void kpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kpassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kpassword1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        mainpanel2.removeAll();
        mainpanel2.repaint();
        mainpanel2.revalidate();

        mainpanel2.add(panelregist);
        mainpanel2.repaint();
        mainpanel2.revalidate();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blogin;
    private javax.swing.JLabel bg_ibu;
    private javax.swing.JLabel bg_login;
    private javax.swing.JLabel bg_regis1;
    private javax.swing.JLabel bg_regis2;
    private javax.swing.JButton btn_cek;
    private javax.swing.JButton btn_regist;
    private javax.swing.JLabel ibu;
    private javax.swing.JLabel ic_close;
    private javax.swing.JLabel ic_key;
    private javax.swing.JLabel ic_posyandu;
    private javax.swing.JLabel ic_profile;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField k_idkader;
    private javax.swing.JPasswordField k_pass;
    private javax.swing.JTextField k_user;
    private javax.swing.JPasswordField kpassword;
    private javax.swing.JPasswordField kpassword1;
    private javax.swing.JTextField kusername;
    private javax.swing.JLabel label_close;
    private javax.swing.JLabel label_idc;
    private javax.swing.JLabel label_kunci;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_profil;
    private javax.swing.JLabel label_sudah;
    private javax.swing.JLabel label_toregist;
    private javax.swing.JPanel mainpanel2;
    private javax.swing.JPanel panellogin;
    private javax.swing.JPanel panelregist;
    private javax.swing.JLabel posyandu;
    private javax.swing.JLabel wp;
    // End of variables declaration//GEN-END:variables
}
