/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectposyandu;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author adrian
 */
public class pembayaran extends javax.swing.JPanel {

    /**
     * Creates new form pembayaran
     */
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public pembayaran() {
        initComponents();
        datatable();
        kosong();
        bt_hapusdata.setEnabled(false);
        bt_ubahdata.setEnabled(false);
        bt_cetak.setEnabled(false);
         setBackground(new Color(0,0,0,0));
         DefaultTableCellRenderer head_render = new DefaultTableCellRenderer(); 
        head_render.setBackground(new Color(32, 136, 203));
        Tbalita.getTableHeader().setOpaque(false);
        Tbalita.getTableHeader().setDefaultRenderer(head_render);
        Tbalita.getTableHeader().setForeground(new Color(255,255,255));
        Tbalita.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        dataPembayaran = new javax.swing.JPanel();
        bt_tambahdata = new javax.swing.JButton();
        bt_ubahdata = new javax.swing.JButton();
        bt_hapusdata = new javax.swing.JButton();
        label_databalita = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbalita = new javax.swing.JTable();
        bt_hapus = new javax.swing.JButton();
        k_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        bt_cetak = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tambahpembayaran = new javax.swing.JPanel();
        k_idtransaksi = new javax.swing.JFormattedTextField();
        k_pembayaran = new javax.swing.JFormattedTextField();
        k_kembalian = new javax.swing.JFormattedTextField();
        k_bayar = new javax.swing.JFormattedTextField();
        k_totalbayar = new javax.swing.JFormattedTextField();
        btn_cek = new javax.swing.JButton();
        k_tl = new com.toedter.calendar.JDateChooser();
        label_id6 = new javax.swing.JLabel();
        label_id5 = new javax.swing.JLabel();
        label_id4 = new javax.swing.JLabel();
        label_data1 = new javax.swing.JLabel();
        label_id3 = new javax.swing.JLabel();
        label_id2 = new javax.swing.JLabel();
        label_id1 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainpanel.setBackground(new java.awt.Color(255, 255, 255));
        mainpanel.setOpaque(false);
        mainpanel.setLayout(new java.awt.CardLayout());

        dataPembayaran.setOpaque(false);
        dataPembayaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_tambahdata.setBackground(new java.awt.Color(7, 155, 7));
        bt_tambahdata.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bt_tambahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new_database-5122.png"))); // NOI18N
        bt_tambahdata.setText("Tambah Data");
        bt_tambahdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });
        dataPembayaran.add(bt_tambahdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 170, 40));

        bt_ubahdata.setBackground(new java.awt.Color(255, 193, 7));
        bt_ubahdata.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bt_ubahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_ubahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/282091.png"))); // NOI18N
        bt_ubahdata.setText("Ubah Data");
        bt_ubahdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        bt_ubahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ubahdataActionPerformed(evt);
            }
        });
        dataPembayaran.add(bt_ubahdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 690, 180, 40));

        bt_hapusdata.setBackground(new java.awt.Color(255, 0, 51));
        bt_hapusdata.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bt_hapusdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/images__1_-removebg-preview.png"))); // NOI18N
        bt_hapusdata.setText("Hapus Data");
        bt_hapusdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        bt_hapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdataActionPerformed(evt);
            }
        });
        dataPembayaran.add(bt_hapusdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 690, 170, 40));

        label_databalita.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        label_databalita.setText("Data Pembayaran");
        dataPembayaran.add(label_databalita, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 46));

        Tbalita.setAutoCreateRowSorter(true);
        Tbalita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tbalita.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Tbalita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NIK", "NAMA", "TANGGAL LAHIR", "ALAMAT", "NO TELEPON"
            }
        ));
        Tbalita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tbalita.setIntercellSpacing(new java.awt.Dimension(5, 10));
        Tbalita.setRowHeight(25);
        Tbalita.getTableHeader().setReorderingAllowed(false);
        Tbalita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbalitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbalita);

        dataPembayaran.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1640, 530));

        bt_hapus.setText("Hapus Data");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });
        dataPembayaran.add(bt_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 1917, 172, 42));

        k_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        k_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_cariActionPerformed(evt);
            }
        });
        k_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                k_cariKeyReleased(evt);
            }
        });
        dataPembayaran.add(k_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 294, 36));

        btn_cari.setBackground(new java.awt.Color(242, 242, 242));
        btn_cari.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pngtree-search-flat-yellow-color-icon-seo-find-research-photo-image_19943406-removebg-preview (1).png"))); // NOI18N
        btn_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        btn_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_cariKeyReleased(evt);
            }
        });
        dataPembayaran.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 40, 36));

        bt_cetak.setBackground(new java.awt.Color(255, 204, 51));
        bt_cetak.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bt_cetak.setForeground(new java.awt.Color(255, 255, 255));
        bt_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/3616288-removebg-preview (1).png"))); // NOI18N
        bt_cetak.setText("Cetak ");
        bt_cetak.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        bt_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cetakActionPerformed(evt);
            }
        });
        dataPembayaran.add(bt_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 690, 170, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ombre-7419016_1280 (1).jpg"))); // NOI18N
        dataPembayaran.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 980));

        mainpanel.add(dataPembayaran, "card2");

        tambahpembayaran.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tambahpembayaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        k_idtransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        k_idtransaksi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        k_idtransaksi.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_idtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_idtransaksiActionPerformed(evt);
            }
        });
        tambahpembayaran.add(k_idtransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 420, 50));

        k_pembayaran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        k_pembayaran.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        k_pembayaran.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_pembayaranActionPerformed(evt);
            }
        });
        tambahpembayaran.add(k_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 420, 50));

        k_kembalian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        k_kembalian.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        k_kembalian.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_kembalianActionPerformed(evt);
            }
        });
        tambahpembayaran.add(k_kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 420, 50));

        k_bayar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        k_bayar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        k_bayar.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_bayarActionPerformed(evt);
            }
        });
        k_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                k_bayarKeyReleased(evt);
            }
        });
        tambahpembayaran.add(k_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 420, 50));

        k_totalbayar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        k_totalbayar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        k_totalbayar.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        k_totalbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_totalbayarActionPerformed(evt);
            }
        });
        tambahpembayaran.add(k_totalbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 420, 50));

        btn_cek.setBackground(new java.awt.Color(0, 0, 204));
        btn_cek.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_cek.setForeground(new java.awt.Color(255, 255, 255));
        btn_cek.setText("CEK");
        btn_cek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        btn_cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekActionPerformed(evt);
            }
        });
        tambahpembayaran.add(btn_cek, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 100, 40));
        tambahpembayaran.add(k_tl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 280, 50));

        label_id6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_id6.setText("Kembalian");
        tambahpembayaran.add(label_id6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 200, 50));

        label_id5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_id5.setText("Bayar");
        tambahpembayaran.add(label_id5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 200, 50));

        label_id4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_id4.setText("ID Transaksi");
        tambahpembayaran.add(label_id4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 170, 30));

        label_data1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        label_data1.setText("TRANSAKSI PEMBAYARAN");
        tambahpembayaran.add(label_data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 350, 46));

        label_id3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_id3.setText("Total Bayar");
        tambahpembayaran.add(label_id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 200, 50));

        label_id2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_id2.setText("Tanggal Pembayaran");
        tambahpembayaran.add(label_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 200, 50));

        label_id1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_id1.setText("Kode Pembayaran");
        tambahpembayaran.add(label_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 170, 30));

        btn_simpan.setBackground(new java.awt.Color(0, 0, 204));
        btn_simpan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/images__2_-removebg-preview (1).png"))); // NOI18N
        btn_simpan.setText("SIMPAN");
        btn_simpan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        tambahpembayaran.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 185, 40));

        bt_batal.setBackground(new java.awt.Color(204, 60, 37));
        bt_batal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bt_batal.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear (1).png"))); // NOI18N
        bt_batal.setText("BATAL");
        bt_batal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });
        tambahpembayaran.add(bt_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, 185, 40));

        btn_ubah.setBackground(new java.awt.Color(0, 0, 204));
        btn_ubah.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_ubah.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/282091.png"))); // NOI18N
        btn_ubah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btn_ubah.setLabel("UBAH");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        tambahpembayaran.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 185, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3169210-removebg-preview.png"))); // NOI18N
        tambahpembayaran.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ombre-7419016_1280 (1).jpg"))); // NOI18N
        jLabel12.setText("l");
        tambahpembayaran.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1920, 1380));

        mainpanel.add(tambahpembayaran, "card3");

        add(mainpanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    protected void datatable(){
        Object[] Baris = {"Kode Pembayaran","Tanggal Pembayaran","Total Harga","Bayar","Kembalian","ID Transaksi"};
        tabmode = new DefaultTableModel (null, Baris);
        String findItem = k_cari.getText();
        try {
            String sql = "SELECT * FROM pembayaran where `kdpembayaran` like '%" + findItem + "%' or `tgl_bayar` like '%" + findItem + "%' or `id_transaksi` like '%" + findItem + "%' order by kdpembayaran asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    "Rp" + hasil.getString(3),
                    "Rp" + hasil.getString(4),
                    "Rp" + hasil.getString(5),
                    hasil.getString(6),
                });
                
            }
            Tbalita.setModel(tabmode); 
        }catch (Exception e){
             JOptionPane.showMessageDialog(null,"datatable gagal "+e);
           }
        
         }
    protected void kosong() {
    k_pembayaran.setText("");
    k_totalbayar.setText("");
    k_bayar.setText("");
    k_kembalian.setText("");
    //k_idtransaksi.setText("");
    k_tl.setDate(null);
}
    
    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        kosong();
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(tambahpembayaran);
        mainpanel.repaint();
        mainpanel.revalidate();
        btn_simpan.setVisible(true);
        btn_simpan.setEnabled(false);
        //btn_ubah.setVisible(false);
        k_idtransaksi.setEditable(false);
        Random rand = new Random();
        Integer random = rand.nextInt(100000);
        k_idtransaksi.setText(random.toString());

    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void bt_ubahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ubahdataActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(tambahpembayaran);
        mainpanel.repaint();
        mainpanel.revalidate();
        btn_ubah.setVisible(true);
        btn_simpan.setVisible(false);
        k_pembayaran.setEditable(false);
        k_idtransaksi.setEditable(false);
        btn_cek.setVisible(false);
    }//GEN-LAST:event_bt_ubahdataActionPerformed

    private void bt_hapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdataActionPerformed

        if(!k_idtransaksi.getText().equals("") && !k_idtransaksi.getText().isEmpty()) {
            bt_hapusdata.setEnabled(true);
            int ok = JOptionPane.showConfirmDialog(null, "hapus", " yakin ingin menghapus?", JOptionPane.YES_NO_OPTION);
            if (ok == 0){
                System.out.println(k_idtransaksi);
                String sql = "DELETE FROM pembayaran WHERE id_transaksi ='"+ k_idtransaksi.getText() + "'" ;
                try {
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                    kosong();
                    //                k_id.requestFocus();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, "data gagal dihapus"+ e);
                }
            }
            datatable();
        } else {
            bt_hapusdata.setEnabled(false);
            JOptionPane.showMessageDialog(null, "tidak ada data yang dihapus");
        }

    }//GEN-LAST:event_bt_hapusdataActionPerformed

    private void TbalitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbalitaMouseClicked

        int bar = Tbalita.getSelectedRow();
        String a = tabmode.getValueAt (bar, 0).toString();
        String b = tabmode.getValueAt (bar, 1).toString();
        String c = tabmode.getValueAt (bar, 2).toString().replaceAll("[^0-9]", "");
        String d = tabmode.getValueAt (bar, 3).toString().replaceAll("[^0-9]", "");
        String e = tabmode.getValueAt (bar, 4).toString().replaceAll("[^0-9]", "");
        String f = tabmode.getValueAt (bar, 5).toString();

        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = formatter.parse(b);
            k_tl.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(balita.class.getName()).log(Level.SEVERE, null, ex);
        }

        // k_id.setText(a)
        k_idtransaksi.setText(f);
        k_totalbayar.setText(c);
        k_pembayaran.setText(a);
        k_bayar.setText(d);
        k_kembalian.setText(e);
        bt_ubahdata.setEnabled(true);
        bt_hapusdata.setEnabled(true);
        bt_cetak.setEnabled(true);
    }//GEN-LAST:event_TbalitaMouseClicked

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", " yakin ingin menghapus?", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            System.out.println(k_idtransaksi);
            String sql = "DELETE FROM balita WHERE kd_balita ="+ k_idtransaksi.getText() ;
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+ e);
            }
        }
        datatable();

    }//GEN-LAST:event_bt_hapusActionPerformed

    private void k_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_cariActionPerformed

    private void k_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_k_cariKeyReleased
        // TODO add your handling code here:
        String findItem = k_cari.getText();
        try{
            String sql = "SELECT * FROM balita where `kd_balita` like '%" + findItem + "%' or `nik` like '%" + findItem + "%' or `nama` like '%" + findItem + "%' order by kd_balita asc";
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5)
                });
            }
            Tbalita.setModel(tabmode);
        } catch (Exception e) {

        }
        datatable();
    }//GEN-LAST:event_k_cariKeyReleased

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        String findItem = k_cari.getText();

    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_cariKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cariKeyReleased

    private void k_idtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_idtransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_idtransaksiActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed

        if(!k_idtransaksi.getText().equals("") && !k_totalbayar.getText().equals("") && !k_tl.getDate().equals(null) && !k_bayar.getText().equals("") && !k_kembalian.getText().equals("") && !k_pembayaran.getText().equals("")) {
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String Kttl = String.valueOf(fm.format(k_tl.getDate()));
            String totalbayar = k_totalbayar.getText().replaceAll("[^0-9]", "");
            String bayar = k_bayar.getText().replaceAll("[^0-9]", "");
            String kembalian = k_kembalian.getText().replaceAll("[^0-9]", "");
            try {
                String sql = "INSERT into pembayaran values (?,?,?,?,?,?) ";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, k_pembayaran.getText());
                stat.setString(2, Kttl);
                stat.setString(3, totalbayar);
                stat.setString(4, bayar);
                 stat.setString(5, kembalian);
                stat.setString(6, k_idtransaksi.getText());
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil disimpan");
                 String jdbc_driver = "com.mysql.jdbc.Driver";
        String user = "root";
        String pass = "";
        String url = "jdbc:mysql://localhost/posyandu3";
        File reportFile = new File(".");
        String dirr = "";

        try {
            Class.forName(jdbc_driver);
            Connection cone = DriverManager.getConnection(url, user, pass);
            Statement stat1 = cone.createStatement();
            String sql1 = "SELECT* from pembayaran where id_transaksi='" + k_idtransaksi.getText() + "'";
            dirr = reportFile.getCanonicalPath() + "/src/projectposyandu/";
            JasperDesign design = JRXmlLoader.load(dirr + "report3.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(design);
            ResultSet rs = stat1.executeQuery(sql1);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap(), rsDataSource);
            JFrame frame = new JFrame("Report");
            frame.getContentPane().add(new JRViewer(jp));
            frame.pack();
            frame.setVisible(true);

        } catch (ClassNotFoundException | SQLException | IOException | JRException ex) {
            JOptionPane.showMessageDialog(null, "\nGagal Mencetak\n" + ex,
                "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
                kosong();
                mainpanel.removeAll();
                mainpanel.repaint();
                mainpanel.revalidate();

                mainpanel.add(dataPembayaran);
                mainpanel.repaint();
                mainpanel.revalidate();

            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal disimpan "+e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Isi semua kolom yang tersedia!");
        }
        datatable();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        mainpanel.removeAll();
        mainpanel.add(dataPembayaran);
        mainpanel.repaint();
        mainpanel.revalidate();
        kosong();
        datatable();
    }//GEN-LAST:event_bt_batalActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String Kttl = String.valueOf(fm.format(k_tl.getDate()));
            String totalbayar = k_totalbayar.getText().replaceAll("[^0-9]", "");
            String bayar = k_bayar.getText().replaceAll("[^0-9]", "");
            String kembalian = k_kembalian.getText().replaceAll("[^0-9]", "");
            String sql = "UPDATE `pembayaran` SET `total_bayar`=?, `tgl_bayar`='"  + Kttl + "', `bayar`=?,`kembalian`=?   WHERE `id_transaksi` = ?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, totalbayar);
            stat.setString(2, bayar);
            stat.setString(3, kembalian);
            stat.setString(4, k_idtransaksi.getText());
            stat.executeUpdate();
            System.out.println(Kttl);
            System.out.println(k_totalbayar.getText());
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            mainpanel.removeAll();
            mainpanel.add(dataPembayaran);
            mainpanel.repaint();
            mainpanel.revalidate();
            datatable();
            kosong();
      } catch(SQLException e) {
          JOptionPane.showMessageDialog(null, "data gagal diubah"+ e);
      }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void k_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_pembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_pembayaranActionPerformed

    private void k_totalbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_totalbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_totalbayarActionPerformed

    private void btn_cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekActionPerformed
        // TODO add your handling code here:
          if(k_pembayaran.getText() != null && !k_pembayaran.getText().isEmpty() && !k_pembayaran.getText().equals("")) {
        try {
         
                 String sql = "SELECT * from pemeriksaan where kdpembayaran = '" + k_pembayaran.getText() + "'"; 
                 java.sql.Statement stat = conn.createStatement();
                    ResultSet hasil = stat.executeQuery(sql);
                     if(!hasil.isBeforeFirst()) {
                        JOptionPane.showMessageDialog(null, "Kode tidak ditemukan, silahkan masukkan kembali kode yang benar");
                        k_pembayaran.setText("");
                        btn_simpan.setEnabled(false);
                     } else {
                         hasil.next();
                         k_totalbayar.setText(hasil.getString("harga"));
                        String sql2 = "SELECT kdpembayaran from pembayaran where kdpembayaran ='" + k_pembayaran.getText() + "'";
                        stat = conn.createStatement();
                        ResultSet hasil2 = stat.executeQuery(sql2);
                        if(!hasil2.isBeforeFirst()) {
                             JOptionPane.showMessageDialog(null, "Kode Pembayaran valid");
                             btn_simpan.setEnabled(true);
                        } else {
                            hasil2.next();
                                if(k_pembayaran.getText().equals(hasil2.getString(1))) {
                                    JOptionPane.showMessageDialog(null, "Kode Pembayaran sudah dibayar!");
                                    kosong();
                                    btn_simpan.setEnabled(false);
                                }
                        }
                     }
                     
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
          } else {
                JOptionPane.showMessageDialog(null, "Masukkan Kode Pembayaran!");
          }
    }//GEN-LAST:event_btn_cekActionPerformed

    private void k_kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_kembalianActionPerformed

    private void k_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_bayarActionPerformed

    private void k_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_k_bayarKeyReleased
        // TODO add your handling code here:
         String totalbayar = k_totalbayar.getText().replaceAll("[^0-9]", "");
         String bayar = k_bayar.getText().replaceAll("[^0-9]", "");
        Integer kembalian = Integer.parseInt(bayar) - Integer.parseInt(totalbayar);
        k_kembalian.setText(kembalian.toString());
        if(kembalian < 0) {
         btn_simpan.setEnabled(false);
        } else {
            btn_simpan.setEnabled(true);
        }
    }//GEN-LAST:event_k_bayarKeyReleased

    private void bt_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cetakActionPerformed
        // TODO add your handling code here:
        bt_cetak.setEnabled(false);
        String jdbc_driver = "com.mysql.jdbc.Driver";
        String user = "root";
        String pass = "";
        String url = "jdbc:mysql://localhost/posyandu3";
        File reportFile = new File(".");
        String dirr = "";

         try {
            Class.forName(jdbc_driver);
            Connection cone = DriverManager.getConnection(url, user, pass);
            Statement stat1 = cone.createStatement();
            String sql = "SELECT* from pembayaran where id_transaksi='" + k_idtransaksi.getText() + "'";
            dirr = reportFile.getCanonicalPath() + "/src/projectposyandu/";
            JasperDesign design = JRXmlLoader.load(dirr + "report3.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(design);
            ResultSet rs = stat1.executeQuery(sql);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap(), rsDataSource);
            JFrame frame = new JFrame("Report");
            frame.getContentPane().add(new JRViewer(jp));
            frame.pack();
            frame.setVisible(true);

        } catch (ClassNotFoundException | SQLException | IOException | JRException ex) {
            JOptionPane.showMessageDialog(null, "\nGagal Mencetak\n" + ex,
                "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_bt_cetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tbalita;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_cetak;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_hapusdata;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JButton bt_ubahdata;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_cek;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JPanel dataPembayaran;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField k_bayar;
    private javax.swing.JTextField k_cari;
    private javax.swing.JFormattedTextField k_idtransaksi;
    private javax.swing.JFormattedTextField k_kembalian;
    private javax.swing.JFormattedTextField k_pembayaran;
    private com.toedter.calendar.JDateChooser k_tl;
    private javax.swing.JFormattedTextField k_totalbayar;
    private javax.swing.JLabel label_data1;
    private javax.swing.JLabel label_databalita;
    private javax.swing.JLabel label_id1;
    private javax.swing.JLabel label_id2;
    private javax.swing.JLabel label_id3;
    private javax.swing.JLabel label_id4;
    private javax.swing.JLabel label_id5;
    private javax.swing.JLabel label_id6;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel tambahpembayaran;
    // End of variables declaration//GEN-END:variables
}
