/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectposyandu;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import koneksi.koneksi;
/**
 *
 * @author PREDATOR
 */
public class Formbalita extends javax.swing.JPanel {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    public Formbalita() {
        initComponents();
        datatable();
        kosong();
        aktif();
    }
    
    protected void aktif(){
        Kid.requestFocus();
    }
    protected void kosong(){
        Kid.setText("");
        KNama.setText("");
        Kttl.setText("");
        Kjk.setText("");
        Kibu.setText("");
        Kalamat.setText("");
        
    }
    protected void datatable(){
        Object[] Baris = {"id","Nama","Tanggal Lahir", "Jenis Kelamin", "Ibu", "Alamat"};
        tabmode = new DefaultTableModel (null, Baris);
        
        String cari = Kcari.getText();
        try {
            String sql = "SELECT * FROM balita where id like '%"+cari+"%' or Nama like '%"+cari+"%' order by id asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6)
                
                });
            }
            Tbalita.setModel(tabmode); 
        }catch (Exception e){
             JOptionPane.showMessageDialog(null,"datatable gagal "+e);
           }
        
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        dataBalita = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbalita = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bt_tambahdata = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        bt_Ubah = new javax.swing.JButton();
        Kcari = new javax.swing.JTextField();
        bt_cari = new javax.swing.JButton();
        tambahBalita = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bt_simpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        KNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Kid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Kttl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Kjk = new javax.swing.JTextField();
        Kibu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Kalamat = new javax.swing.JTextField();
        ubahbalita = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        bt_ubah = new javax.swing.JButton();
        bt_batal1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        KNama1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Kid1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Kttl1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Kjk1 = new javax.swing.JTextField();
        Kibu1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Kalamat1 = new javax.swing.JTextField();
        hapusbalita = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        bt_hapusdata = new javax.swing.JButton();
        bt_batal2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        KNama2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Kid2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Kttl2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Kjk2 = new javax.swing.JTextField();
        Kibu2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Kalamat2 = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        mainpanel.setLayout(new java.awt.CardLayout());

        Tbalita.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        Tbalita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NAMA", "Tanggal Lahir", "Jenis Kelamin", "Ibu", "Alamat"
            }
        ));
        Tbalita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tbalita.setIntercellSpacing(new java.awt.Dimension(5, 10));
        Tbalita.setRowHeight(25);
        jScrollPane1.setViewportView(Tbalita);
        if (Tbalita.getColumnModel().getColumnCount() > 0) {
            Tbalita.getColumnModel().getColumn(0).setHeaderValue("NAMA");
            Tbalita.getColumnModel().getColumn(1).setHeaderValue("Tanggal Lahir");
            Tbalita.getColumnModel().getColumn(2).setHeaderValue("Jenis Kelamin");
            Tbalita.getColumnModel().getColumn(3).setHeaderValue("Ibu");
            Tbalita.getColumnModel().getColumn(4).setHeaderValue("Alamat");
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("DATA BALITA");

        bt_tambahdata.setText("Tambah Data");
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });

        bt_hapus.setText("Hapus Data");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_Ubah.setText("Ubah Data");
        bt_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_UbahActionPerformed(evt);
            }
        });

        bt_cari.setText("CARI");

        javax.swing.GroupLayout dataBalitaLayout = new javax.swing.GroupLayout(dataBalita);
        dataBalita.setLayout(dataBalitaLayout);
        dataBalitaLayout.setHorizontalGroup(
            dataBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBalitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1820, Short.MAX_VALUE)
                    .addGroup(dataBalitaLayout.createSequentialGroup()
                        .addGroup(dataBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataBalitaLayout.createSequentialGroup()
                                .addComponent(Kcari, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dataBalitaLayout.createSequentialGroup()
                                .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        dataBalitaLayout.setVerticalGroup(
            dataBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBalitaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dataBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Kcari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        mainpanel.add(dataBalita, "card2");

        tambahBalita.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setText("DATA BALITA");

        bt_simpan.setText("SIMPAN");
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        bt_batal.setText("BATAL");
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        jLabel3.setText("id");

        KNama.setText("jTextField1");

        jLabel4.setText("Nama");

        Kid.setText("jTextField2");

        jLabel5.setText("Tanggal Lahir");

        Kttl.setText("jTextField1");

        jLabel6.setText("Jenis Kelamin");

        Kjk.setText("jTextField1");

        Kibu.setText("jTextField1");
        Kibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KibuActionPerformed(evt);
            }
        });

        jLabel7.setText("Ibu");

        jLabel8.setText("Alamat ");

        Kalamat.setText("jTextField6");

        javax.swing.GroupLayout tambahBalitaLayout = new javax.swing.GroupLayout(tambahBalita);
        tambahBalita.setLayout(tambahBalitaLayout);
        tambahBalitaLayout.setHorizontalGroup(
            tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBalitaLayout.createSequentialGroup()
                .addGroup(tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahBalitaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahBalitaLayout.createSequentialGroup()
                                .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tambahBalitaLayout.createSequentialGroup()
                                .addGroup(tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(KNama)
                                    .addComponent(Kid)
                                    .addComponent(Kttl, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                    .addComponent(Kjk, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                    .addComponent(Kibu, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                    .addComponent(Kalamat)))))
                    .addGroup(tambahBalitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1136, Short.MAX_VALUE))
        );
        tambahBalitaLayout.setVerticalGroup(
            tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBalitaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Kid, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KNama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kttl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kjk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kibu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tambahBalitaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Kalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahBalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(465, Short.MAX_VALUE))
        );

        mainpanel.add(tambahBalita, "card2");

        ubahbalita.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel9.setText("DATA BALITA");

        bt_ubah.setText("UBAH");
        bt_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ubahActionPerformed(evt);
            }
        });

        bt_batal1.setText("BATAL");
        bt_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batal1ActionPerformed(evt);
            }
        });

        jLabel10.setText("id");

        jLabel11.setText("Nama");

        jLabel12.setText("Tanggal Lahir");

        jLabel13.setText("Jenis Kelamin");

        Kibu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kibu1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Ibu");

        jLabel15.setText("Alamat ");

        javax.swing.GroupLayout ubahbalitaLayout = new javax.swing.GroupLayout(ubahbalita);
        ubahbalita.setLayout(ubahbalitaLayout);
        ubahbalitaLayout.setHorizontalGroup(
            ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubahbalitaLayout.createSequentialGroup()
                .addGroup(ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ubahbalitaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ubahbalitaLayout.createSequentialGroup()
                                .addComponent(bt_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ubahbalitaLayout.createSequentialGroup()
                                .addGroup(ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(KNama1)
                                    .addComponent(Kid1)
                                    .addComponent(Kttl1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                    .addComponent(Kjk1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                    .addComponent(Kibu1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                    .addComponent(Kalamat1)))))
                    .addGroup(ubahbalitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1136, Short.MAX_VALUE))
        );
        ubahbalitaLayout.setVerticalGroup(
            ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubahbalitaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Kid1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(28, 28, 28)
                .addGroup(ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kttl1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kjk1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kibu1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ubahbalitaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Kalamat1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ubahbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(465, Short.MAX_VALUE))
        );

        mainpanel.add(ubahbalita, "card2");

        hapusbalita.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel16.setText("DATA BALITA");

        bt_hapusdata.setText("HAPUS");
        bt_hapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdataActionPerformed(evt);
            }
        });

        bt_batal2.setText("BATAL");
        bt_batal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batal2ActionPerformed(evt);
            }
        });

        jLabel17.setText("id");

        jLabel18.setText("Nama");

        jLabel19.setText("Tanggal Lahir");

        jLabel20.setText("Jenis Kelamin");

        Kibu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kibu2ActionPerformed(evt);
            }
        });

        jLabel21.setText("Ibu");

        jLabel22.setText("Alamat ");

        javax.swing.GroupLayout hapusbalitaLayout = new javax.swing.GroupLayout(hapusbalita);
        hapusbalita.setLayout(hapusbalitaLayout);
        hapusbalitaLayout.setHorizontalGroup(
            hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusbalitaLayout.createSequentialGroup()
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hapusbalitaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hapusbalitaLayout.createSequentialGroup()
                                .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_batal2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hapusbalitaLayout.createSequentialGroup()
                                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(KNama2)
                                    .addComponent(Kid2)
                                    .addComponent(Kttl2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                    .addComponent(Kjk2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                    .addComponent(Kibu2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                    .addComponent(Kalamat2)))))
                    .addGroup(hapusbalitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1136, Short.MAX_VALUE))
        );
        hapusbalitaLayout.setVerticalGroup(
            hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusbalitaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Kid2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KNama2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(28, 28, 28)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kttl2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kjk2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kibu2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(hapusbalitaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Kalamat2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hapusbalitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(465, Short.MAX_VALUE))
        );

        mainpanel.add(hapusbalita, "card2");

        add(mainpanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
       String sql = "INSERT INTO balita values (?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, Kid.getText());
            stat.setString(2, KNama.getText());
            stat.setString(3, Kttl.getText());
            stat.setString(4, Kjk.getText());
            stat.setString(5, Kibu.getText());
            stat.setString(6, Kalamat.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            Kid.requestFocus();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan "+e);
        }
        datatable();
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void KibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KibuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KibuActionPerformed

    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(tambahBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        
        
    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        mainpanel.removeAll();
        mainpanel.add(dataBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        kosong();
        datatable();
    }//GEN-LAST:event_bt_batalActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(hapusbalita);
        mainpanel.repaint();
        
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ubahActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(ubahbalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        try{
            String sql = "UPDATE balita set id=?,Nama=?,Tanggal Lahir=?,Jenis Kelamin=?,Ibu=?,Alamat=? where id ='"+Kid.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, Kid.getText());
            stat.setString(2, KNama.getText());
            stat.setString(3, Kttl.getText());
            stat.setString(4, Kjk.getText());
            stat.setString(5, Kibu.getText());
            stat.setString(6, Kalamat.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI UBAH");
            kosong();
            Kid.requestFocus();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah"+ e);
        }
        datatable();
    }//GEN-LAST:event_bt_ubahActionPerformed

    private void bt_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batal1ActionPerformed
        mainpanel.removeAll();
        mainpanel.add(dataBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        kosong();
        datatable();
    }//GEN-LAST:event_bt_batal1ActionPerformed

    private void Kibu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kibu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kibu1ActionPerformed

    private void bt_hapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdataActionPerformed
        
        int ok = JOptionPane.showConfirmDialog(null, "hapus", " yakin ingin menghapus?", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "DELETE FROM balita WHERE id = '"+Kid.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                Kid.requestFocus();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+ e);
            }
            datatable();
        }
    }//GEN-LAST:event_bt_hapusdataActionPerformed

    private void bt_batal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batal2ActionPerformed
        mainpanel.removeAll();
        mainpanel.add(dataBalita);
        mainpanel.repaint();
        mainpanel.revalidate();
        kosong();
        datatable();
    }//GEN-LAST:event_bt_batal2ActionPerformed

    private void Kibu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kibu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kibu2ActionPerformed

    private void bt_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_UbahActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(ubahbalita);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_bt_UbahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KNama;
    private javax.swing.JTextField KNama1;
    private javax.swing.JTextField KNama2;
    private javax.swing.JTextField Kalamat;
    private javax.swing.JTextField Kalamat1;
    private javax.swing.JTextField Kalamat2;
    private javax.swing.JTextField Kcari;
    private javax.swing.JTextField Kibu;
    private javax.swing.JTextField Kibu1;
    private javax.swing.JTextField Kibu2;
    private javax.swing.JTextField Kid;
    private javax.swing.JTextField Kid1;
    private javax.swing.JTextField Kid2;
    private javax.swing.JTextField Kjk;
    private javax.swing.JTextField Kjk1;
    private javax.swing.JTextField Kjk2;
    private javax.swing.JTextField Kttl;
    private javax.swing.JTextField Kttl1;
    private javax.swing.JTextField Kttl2;
    private javax.swing.JTable Tbalita;
    private javax.swing.JButton bt_Ubah;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_batal1;
    private javax.swing.JButton bt_batal2;
    private javax.swing.JButton bt_cari;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_hapusdata;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JButton bt_ubah;
    private javax.swing.JPanel dataBalita;
    private javax.swing.JPanel hapusbalita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel tambahBalita;
    private javax.swing.JPanel ubahbalita;
    // End of variables declaration//GEN-END:variables
}
